/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BoardControllerCreateBoardRequest,
  BoardControllerCreateBoardResponse,
  BoardControllerDeleteBoardRequest,
  BoardControllerDeleteBoardResponse,
  BoardControllerGetBoardRequest,
  BoardControllerGetBoardResponse,
  BoardControllerListBoardsResponse,
  ModelsErrorResponse,
} from '../models/index';
import {
    BoardControllerCreateBoardRequestFromJSON,
    BoardControllerCreateBoardRequestToJSON,
    BoardControllerCreateBoardResponseFromJSON,
    BoardControllerCreateBoardResponseToJSON,
    BoardControllerDeleteBoardRequestFromJSON,
    BoardControllerDeleteBoardRequestToJSON,
    BoardControllerDeleteBoardResponseFromJSON,
    BoardControllerDeleteBoardResponseToJSON,
    BoardControllerGetBoardRequestFromJSON,
    BoardControllerGetBoardRequestToJSON,
    BoardControllerGetBoardResponseFromJSON,
    BoardControllerGetBoardResponseToJSON,
    BoardControllerListBoardsResponseFromJSON,
    BoardControllerListBoardsResponseToJSON,
    ModelsErrorResponseFromJSON,
    ModelsErrorResponseToJSON,
} from '../models/index';

export interface ApiV1BoardsCreatePostRequest {
    request: BoardControllerCreateBoardRequest;
}

export interface ApiV1BoardsDeletePostRequest {
    request: BoardControllerDeleteBoardRequest;
}

export interface ApiV1BoardsGetGetRequest {
    request: BoardControllerGetBoardRequest;
}

/**
 * 
 */
export class BoardsApi extends runtime.BaseAPI {

    /**
     * Create a new board with the given name
     * Create a new board
     */
    async apiV1BoardsCreatePostRaw(requestParameters: ApiV1BoardsCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BoardControllerCreateBoardResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1BoardsCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-CSRF-Token"] = await this.configuration.apiKey("X-CSRF-Token"); // csrf authentication
        }

        const response = await this.request({
            path: `/api/v1/boards/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BoardControllerCreateBoardRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BoardControllerCreateBoardResponseFromJSON(jsonValue));
    }

    /**
     * Create a new board with the given name
     * Create a new board
     */
    async apiV1BoardsCreatePost(requestParameters: ApiV1BoardsCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BoardControllerCreateBoardResponse> {
        const response = await this.apiV1BoardsCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a board by ID
     * Delete a board
     */
    async apiV1BoardsDeletePostRaw(requestParameters: ApiV1BoardsDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BoardControllerDeleteBoardResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1BoardsDeletePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-CSRF-Token"] = await this.configuration.apiKey("X-CSRF-Token"); // csrf authentication
        }

        const response = await this.request({
            path: `/api/v1/boards/delete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BoardControllerDeleteBoardRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BoardControllerDeleteBoardResponseFromJSON(jsonValue));
    }

    /**
     * Delete a board by ID
     * Delete a board
     */
    async apiV1BoardsDeletePost(requestParameters: ApiV1BoardsDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BoardControllerDeleteBoardResponse> {
        const response = await this.apiV1BoardsDeletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a board by ID
     * Get a board
     */
    async apiV1BoardsGetGetRaw(requestParameters: ApiV1BoardsGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BoardControllerGetBoardResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1BoardsGetGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/boards/get`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: BoardControllerGetBoardRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BoardControllerGetBoardResponseFromJSON(jsonValue));
    }

    /**
     * Get a board by ID
     * Get a board
     */
    async apiV1BoardsGetGet(requestParameters: ApiV1BoardsGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BoardControllerGetBoardResponse> {
        const response = await this.apiV1BoardsGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all boards for the current user
     * List all boards
     */
    async apiV1BoardsListGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BoardControllerListBoardsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/boards/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BoardControllerListBoardsResponseFromJSON(jsonValue));
    }

    /**
     * List all boards for the current user
     * List all boards
     */
    async apiV1BoardsListGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BoardControllerListBoardsResponse> {
        const response = await this.apiV1BoardsListGetRaw(initOverrides);
        return await response.value();
    }

}
