/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommentControllerCreateCommentRequest,
  CommentControllerCreateCommentResponse,
  CommentControllerDeleteCommentRequest,
  CommentControllerDeleteCommentResponse,
  CommentControllerEditCommentRequest,
  CommentControllerEditCommentResponse,
  ModelsErrorResponse,
} from '../models/index';
import {
    CommentControllerCreateCommentRequestFromJSON,
    CommentControllerCreateCommentRequestToJSON,
    CommentControllerCreateCommentResponseFromJSON,
    CommentControllerCreateCommentResponseToJSON,
    CommentControllerDeleteCommentRequestFromJSON,
    CommentControllerDeleteCommentRequestToJSON,
    CommentControllerDeleteCommentResponseFromJSON,
    CommentControllerDeleteCommentResponseToJSON,
    CommentControllerEditCommentRequestFromJSON,
    CommentControllerEditCommentRequestToJSON,
    CommentControllerEditCommentResponseFromJSON,
    CommentControllerEditCommentResponseToJSON,
    ModelsErrorResponseFromJSON,
    ModelsErrorResponseToJSON,
} from '../models/index';

export interface ApiV1CommentsCreatePostRequest {
    request: CommentControllerCreateCommentRequest;
}

export interface ApiV1CommentsDeletePostRequest {
    request: CommentControllerDeleteCommentRequest;
}

export interface ApiV1CommentsEditPostRequest {
    request: CommentControllerEditCommentRequest;
}

/**
 * 
 */
export class CommentsApi extends runtime.BaseAPI {

    /**
     * Create a comment for a task
     * Create a comment
     */
    async apiV1CommentsCreatePostRaw(requestParameters: ApiV1CommentsCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentControllerCreateCommentResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1CommentsCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-CSRF-Token"] = await this.configuration.apiKey("X-CSRF-Token"); // csrf authentication
        }

        const response = await this.request({
            path: `/api/v1/comments/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CommentControllerCreateCommentRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentControllerCreateCommentResponseFromJSON(jsonValue));
    }

    /**
     * Create a comment for a task
     * Create a comment
     */
    async apiV1CommentsCreatePost(requestParameters: ApiV1CommentsCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentControllerCreateCommentResponse> {
        const response = await this.apiV1CommentsCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a comment
     * Delete a comment
     */
    async apiV1CommentsDeletePostRaw(requestParameters: ApiV1CommentsDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentControllerDeleteCommentResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1CommentsDeletePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-CSRF-Token"] = await this.configuration.apiKey("X-CSRF-Token"); // csrf authentication
        }

        const response = await this.request({
            path: `/api/v1/comments/delete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CommentControllerDeleteCommentRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentControllerDeleteCommentResponseFromJSON(jsonValue));
    }

    /**
     * Delete a comment
     * Delete a comment
     */
    async apiV1CommentsDeletePost(requestParameters: ApiV1CommentsDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentControllerDeleteCommentResponse> {
        const response = await this.apiV1CommentsDeletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Edit a comment
     * Edit a comment
     */
    async apiV1CommentsEditPostRaw(requestParameters: ApiV1CommentsEditPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentControllerEditCommentResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1CommentsEditPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-CSRF-Token"] = await this.configuration.apiKey("X-CSRF-Token"); // csrf authentication
        }

        const response = await this.request({
            path: `/api/v1/comments/edit`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CommentControllerEditCommentRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentControllerEditCommentResponseFromJSON(jsonValue));
    }

    /**
     * Edit a comment
     * Edit a comment
     */
    async apiV1CommentsEditPost(requestParameters: ApiV1CommentsEditPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentControllerEditCommentResponse> {
        const response = await this.apiV1CommentsEditPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
