/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MiscControllerAppNameResponse,
} from '../models/index';
import {
    MiscControllerAppNameResponseFromJSON,
    MiscControllerAppNameResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class MiscApi extends runtime.BaseAPI {

    /**
     * Get the app name
     * Get the app name
     */
    async apiV1MiscAppnameGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MiscControllerAppNameResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/misc/appname`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MiscControllerAppNameResponseFromJSON(jsonValue));
    }

    /**
     * Get the app name
     * Get the app name
     */
    async apiV1MiscAppnameGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MiscControllerAppNameResponse> {
        const response = await this.apiV1MiscAppnameGetRaw(initOverrides);
        return await response.value();
    }

}
