/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelsErrorResponse,
  SampleDataControllerInsertSampleDataRequest,
  SampleDataControllerInsertSampleDataResponse,
} from '../models/index';
import {
    ModelsErrorResponseFromJSON,
    ModelsErrorResponseToJSON,
    SampleDataControllerInsertSampleDataRequestFromJSON,
    SampleDataControllerInsertSampleDataRequestToJSON,
    SampleDataControllerInsertSampleDataResponseFromJSON,
    SampleDataControllerInsertSampleDataResponseToJSON,
} from '../models/index';

export interface ApiV1SampleDataInsertPostRequest {
    request: SampleDataControllerInsertSampleDataRequest;
}

/**
 * 
 */
export class SampleDataApi extends runtime.BaseAPI {

    /**
     * Insert sample data into the database for a specific board
     * Insert sample data into the database for a specific board
     */
    async apiV1SampleDataInsertPostRaw(requestParameters: ApiV1SampleDataInsertPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SampleDataControllerInsertSampleDataResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1SampleDataInsertPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-CSRF-Token"] = await this.configuration.apiKey("X-CSRF-Token"); // csrf authentication
        }

        const response = await this.request({
            path: `/api/v1/sample-data/insert`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SampleDataControllerInsertSampleDataRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SampleDataControllerInsertSampleDataResponseFromJSON(jsonValue));
    }

    /**
     * Insert sample data into the database for a specific board
     * Insert sample data into the database for a specific board
     */
    async apiV1SampleDataInsertPost(requestParameters: ApiV1SampleDataInsertPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SampleDataControllerInsertSampleDataResponse> {
        const response = await this.apiV1SampleDataInsertPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
