/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelsErrorResponse,
  TaskControllerChangeAssigneeRequest,
  TaskControllerChangeAssigneeResponse,
  TaskControllerCreateTaskRequest,
  TaskControllerCreateTaskResponse,
  TaskControllerDeleteTaskRequest,
  TaskControllerDeleteTaskResponse,
  TaskControllerEditTaskRequest,
  TaskControllerEditTaskResponse,
  TaskControllerGetTaskQueryResponse,
  TaskControllerGetTaskResponse,
  TaskControllerMoveTaskRequest,
  TaskControllerMoveTaskResponse,
} from '../models/index';
import {
    ModelsErrorResponseFromJSON,
    ModelsErrorResponseToJSON,
    TaskControllerChangeAssigneeRequestFromJSON,
    TaskControllerChangeAssigneeRequestToJSON,
    TaskControllerChangeAssigneeResponseFromJSON,
    TaskControllerChangeAssigneeResponseToJSON,
    TaskControllerCreateTaskRequestFromJSON,
    TaskControllerCreateTaskRequestToJSON,
    TaskControllerCreateTaskResponseFromJSON,
    TaskControllerCreateTaskResponseToJSON,
    TaskControllerDeleteTaskRequestFromJSON,
    TaskControllerDeleteTaskRequestToJSON,
    TaskControllerDeleteTaskResponseFromJSON,
    TaskControllerDeleteTaskResponseToJSON,
    TaskControllerEditTaskRequestFromJSON,
    TaskControllerEditTaskRequestToJSON,
    TaskControllerEditTaskResponseFromJSON,
    TaskControllerEditTaskResponseToJSON,
    TaskControllerGetTaskQueryResponseFromJSON,
    TaskControllerGetTaskQueryResponseToJSON,
    TaskControllerGetTaskResponseFromJSON,
    TaskControllerGetTaskResponseToJSON,
    TaskControllerMoveTaskRequestFromJSON,
    TaskControllerMoveTaskRequestToJSON,
    TaskControllerMoveTaskResponseFromJSON,
    TaskControllerMoveTaskResponseToJSON,
} from '../models/index';

export interface ApiV1TasksChangeAssigneePostRequest {
    request: TaskControllerChangeAssigneeRequest;
}

export interface ApiV1TasksCreatePostRequest {
    request: TaskControllerCreateTaskRequest;
}

export interface ApiV1TasksDeletePostRequest {
    request: TaskControllerDeleteTaskRequest;
}

export interface ApiV1TasksEditPostRequest {
    request: TaskControllerEditTaskRequest;
}

export interface ApiV1TasksGetIdGetRequest {
    id: number;
}

export interface ApiV1TasksGetQueryQueryGetRequest {
    query: string;
}

export interface ApiV1TasksMovePostRequest {
    request: TaskControllerMoveTaskRequest;
}

/**
 * 
 */
export class TasksApi extends runtime.BaseAPI {

    /**
     * Change the assignee of a task
     * Change assignee of a task
     */
    async apiV1TasksChangeAssigneePostRaw(requestParameters: ApiV1TasksChangeAssigneePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskControllerChangeAssigneeResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1TasksChangeAssigneePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-CSRF-Token"] = await this.configuration.apiKey("X-CSRF-Token"); // csrf authentication
        }

        const response = await this.request({
            path: `/api/v1/tasks/change-assignee`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskControllerChangeAssigneeRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskControllerChangeAssigneeResponseFromJSON(jsonValue));
    }

    /**
     * Change the assignee of a task
     * Change assignee of a task
     */
    async apiV1TasksChangeAssigneePost(requestParameters: ApiV1TasksChangeAssigneePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskControllerChangeAssigneeResponse> {
        const response = await this.apiV1TasksChangeAssigneePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a task
     * Create a task
     */
    async apiV1TasksCreatePostRaw(requestParameters: ApiV1TasksCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskControllerCreateTaskResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1TasksCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-CSRF-Token"] = await this.configuration.apiKey("X-CSRF-Token"); // csrf authentication
        }

        const response = await this.request({
            path: `/api/v1/tasks/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskControllerCreateTaskRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskControllerCreateTaskResponseFromJSON(jsonValue));
    }

    /**
     * Create a task
     * Create a task
     */
    async apiV1TasksCreatePost(requestParameters: ApiV1TasksCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskControllerCreateTaskResponse> {
        const response = await this.apiV1TasksCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a task
     * Delete a task
     */
    async apiV1TasksDeletePostRaw(requestParameters: ApiV1TasksDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskControllerDeleteTaskResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1TasksDeletePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-CSRF-Token"] = await this.configuration.apiKey("X-CSRF-Token"); // csrf authentication
        }

        const response = await this.request({
            path: `/api/v1/tasks/delete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskControllerDeleteTaskRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskControllerDeleteTaskResponseFromJSON(jsonValue));
    }

    /**
     * Delete a task
     * Delete a task
     */
    async apiV1TasksDeletePost(requestParameters: ApiV1TasksDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskControllerDeleteTaskResponse> {
        const response = await this.apiV1TasksDeletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Edit a task
     * Edit a task
     */
    async apiV1TasksEditPostRaw(requestParameters: ApiV1TasksEditPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskControllerEditTaskResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1TasksEditPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-CSRF-Token"] = await this.configuration.apiKey("X-CSRF-Token"); // csrf authentication
        }

        const response = await this.request({
            path: `/api/v1/tasks/edit`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskControllerEditTaskRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskControllerEditTaskResponseFromJSON(jsonValue));
    }

    /**
     * Edit a task
     * Edit a task
     */
    async apiV1TasksEditPost(requestParameters: ApiV1TasksEditPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskControllerEditTaskResponse> {
        const response = await this.apiV1TasksEditPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a task
     * Get a task
     */
    async apiV1TasksGetIdGetRaw(requestParameters: ApiV1TasksGetIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskControllerGetTaskResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1TasksGetIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/tasks/get/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskControllerGetTaskResponseFromJSON(jsonValue));
    }

    /**
     * Get a task
     * Get a task
     */
    async apiV1TasksGetIdGet(requestParameters: ApiV1TasksGetIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskControllerGetTaskResponse> {
        const response = await this.apiV1TasksGetIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get tasks with a query
     * Get tasks with a query
     */
    async apiV1TasksGetQueryQueryGetRaw(requestParameters: ApiV1TasksGetQueryQueryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskControllerGetTaskQueryResponse>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling apiV1TasksGetQueryQueryGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/tasks/get-query/{query}`.replace(`{${"query"}}`, encodeURIComponent(String(requestParameters['query']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskControllerGetTaskQueryResponseFromJSON(jsonValue));
    }

    /**
     * Get tasks with a query
     * Get tasks with a query
     */
    async apiV1TasksGetQueryQueryGet(requestParameters: ApiV1TasksGetQueryQueryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskControllerGetTaskQueryResponse> {
        const response = await this.apiV1TasksGetQueryQueryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Move a task to a different column and swimlane, and update its position
     * Move a task
     */
    async apiV1TasksMovePostRaw(requestParameters: ApiV1TasksMovePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskControllerMoveTaskResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1TasksMovePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-CSRF-Token"] = await this.configuration.apiKey("X-CSRF-Token"); // csrf authentication
        }

        const response = await this.request({
            path: `/api/v1/tasks/move`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskControllerMoveTaskRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskControllerMoveTaskResponseFromJSON(jsonValue));
    }

    /**
     * Move a task to a different column and swimlane, and update its position
     * Move a task
     */
    async apiV1TasksMovePost(requestParameters: ApiV1TasksMovePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskControllerMoveTaskResponse> {
        const response = await this.apiV1TasksMovePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
