/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelsErrorResponse,
  TaskControllerCreateTaskRequest,
  TaskControllerCreateTaskResponse,
  TaskControllerDeleteTaskRequest,
  TaskControllerDeleteTaskResponse,
  TaskControllerEditTaskRequest,
  TaskControllerEditTaskResponse,
  TaskControllerGetTaskQueryRequest,
  TaskControllerGetTaskQueryResponse,
  TaskControllerGetTaskRequest,
  TaskControllerGetTaskResponse,
} from '../models/index';
import {
    ModelsErrorResponseFromJSON,
    ModelsErrorResponseToJSON,
    TaskControllerCreateTaskRequestFromJSON,
    TaskControllerCreateTaskRequestToJSON,
    TaskControllerCreateTaskResponseFromJSON,
    TaskControllerCreateTaskResponseToJSON,
    TaskControllerDeleteTaskRequestFromJSON,
    TaskControllerDeleteTaskRequestToJSON,
    TaskControllerDeleteTaskResponseFromJSON,
    TaskControllerDeleteTaskResponseToJSON,
    TaskControllerEditTaskRequestFromJSON,
    TaskControllerEditTaskRequestToJSON,
    TaskControllerEditTaskResponseFromJSON,
    TaskControllerEditTaskResponseToJSON,
    TaskControllerGetTaskQueryRequestFromJSON,
    TaskControllerGetTaskQueryRequestToJSON,
    TaskControllerGetTaskQueryResponseFromJSON,
    TaskControllerGetTaskQueryResponseToJSON,
    TaskControllerGetTaskRequestFromJSON,
    TaskControllerGetTaskRequestToJSON,
    TaskControllerGetTaskResponseFromJSON,
    TaskControllerGetTaskResponseToJSON,
} from '../models/index';

export interface ApiV1TasksCreatePostRequest {
    request: TaskControllerCreateTaskRequest;
}

export interface ApiV1TasksDeletePostRequest {
    request: TaskControllerDeleteTaskRequest;
}

export interface ApiV1TasksEditPostRequest {
    request: TaskControllerEditTaskRequest;
}

export interface ApiV1TasksGetGetRequest {
    request: TaskControllerGetTaskRequest;
}

export interface ApiV1TasksGetQueryGetRequest {
    request: TaskControllerGetTaskQueryRequest;
}

/**
 * 
 */
export class TasksApi extends runtime.BaseAPI {

    /**
     * Create a task
     * Create a task
     */
    async apiV1TasksCreatePostRaw(requestParameters: ApiV1TasksCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskControllerCreateTaskResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1TasksCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-CSRF-Token"] = await this.configuration.apiKey("X-CSRF-Token"); // csrf authentication
        }

        const response = await this.request({
            path: `/api/v1/tasks/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskControllerCreateTaskRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskControllerCreateTaskResponseFromJSON(jsonValue));
    }

    /**
     * Create a task
     * Create a task
     */
    async apiV1TasksCreatePost(requestParameters: ApiV1TasksCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskControllerCreateTaskResponse> {
        const response = await this.apiV1TasksCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a task
     * Delete a task
     */
    async apiV1TasksDeletePostRaw(requestParameters: ApiV1TasksDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskControllerDeleteTaskResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1TasksDeletePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-CSRF-Token"] = await this.configuration.apiKey("X-CSRF-Token"); // csrf authentication
        }

        const response = await this.request({
            path: `/api/v1/tasks/delete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskControllerDeleteTaskRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskControllerDeleteTaskResponseFromJSON(jsonValue));
    }

    /**
     * Delete a task
     * Delete a task
     */
    async apiV1TasksDeletePost(requestParameters: ApiV1TasksDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskControllerDeleteTaskResponse> {
        const response = await this.apiV1TasksDeletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Edit a task
     * Edit a task
     */
    async apiV1TasksEditPostRaw(requestParameters: ApiV1TasksEditPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskControllerEditTaskResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1TasksEditPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-CSRF-Token"] = await this.configuration.apiKey("X-CSRF-Token"); // csrf authentication
        }

        const response = await this.request({
            path: `/api/v1/tasks/edit`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaskControllerEditTaskRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskControllerEditTaskResponseFromJSON(jsonValue));
    }

    /**
     * Edit a task
     * Edit a task
     */
    async apiV1TasksEditPost(requestParameters: ApiV1TasksEditPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskControllerEditTaskResponse> {
        const response = await this.apiV1TasksEditPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a task
     * Get a task
     */
    async apiV1TasksGetGetRaw(requestParameters: ApiV1TasksGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskControllerGetTaskResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1TasksGetGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/tasks/get`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: TaskControllerGetTaskRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskControllerGetTaskResponseFromJSON(jsonValue));
    }

    /**
     * Get a task
     * Get a task
     */
    async apiV1TasksGetGet(requestParameters: ApiV1TasksGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskControllerGetTaskResponse> {
        const response = await this.apiV1TasksGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get tasks with a query
     * Get tasks with a query
     */
    async apiV1TasksGetQueryGetRaw(requestParameters: ApiV1TasksGetQueryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskControllerGetTaskQueryResponse>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling apiV1TasksGetQueryGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/tasks/get-query`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: TaskControllerGetTaskQueryRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskControllerGetTaskQueryResponseFromJSON(jsonValue));
    }

    /**
     * Get tasks with a query
     * Get tasks with a query
     */
    async apiV1TasksGetQueryGet(requestParameters: ApiV1TasksGetQueryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskControllerGetTaskQueryResponse> {
        const response = await this.apiV1TasksGetQueryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
