/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminControllerRemoveUserResponse
 */
export interface AdminControllerRemoveUserResponse {
    /**
     * 
     * @type {string}
     * @memberof AdminControllerRemoveUserResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the AdminControllerRemoveUserResponse interface.
 */
export function instanceOfAdminControllerRemoveUserResponse(value: object): value is AdminControllerRemoveUserResponse {
    return true;
}

export function AdminControllerRemoveUserResponseFromJSON(json: any): AdminControllerRemoveUserResponse {
    return AdminControllerRemoveUserResponseFromJSONTyped(json, false);
}

export function AdminControllerRemoveUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminControllerRemoveUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function AdminControllerRemoveUserResponseToJSON(json: any): AdminControllerRemoveUserResponse {
    return AdminControllerRemoveUserResponseToJSONTyped(json, false);
}

export function AdminControllerRemoveUserResponseToJSONTyped(value?: AdminControllerRemoveUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

