/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsUser } from './ModelsUser';
import {
    ModelsUserFromJSON,
    ModelsUserFromJSONTyped,
    ModelsUserToJSON,
    ModelsUserToJSONTyped,
} from './ModelsUser';

/**
 * 
 * @export
 * @interface AdminControllerUpdateUserRoleResponse
 */
export interface AdminControllerUpdateUserRoleResponse {
    /**
     * 
     * @type {string}
     * @memberof AdminControllerUpdateUserRoleResponse
     */
    message?: string;
    /**
     * 
     * @type {ModelsUser}
     * @memberof AdminControllerUpdateUserRoleResponse
     */
    user?: ModelsUser;
}

/**
 * Check if a given object implements the AdminControllerUpdateUserRoleResponse interface.
 */
export function instanceOfAdminControllerUpdateUserRoleResponse(value: object): value is AdminControllerUpdateUserRoleResponse {
    return true;
}

export function AdminControllerUpdateUserRoleResponseFromJSON(json: any): AdminControllerUpdateUserRoleResponse {
    return AdminControllerUpdateUserRoleResponseFromJSONTyped(json, false);
}

export function AdminControllerUpdateUserRoleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminControllerUpdateUserRoleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'user': json['user'] == null ? undefined : ModelsUserFromJSON(json['user']),
    };
}

export function AdminControllerUpdateUserRoleResponseToJSON(json: any): AdminControllerUpdateUserRoleResponse {
    return AdminControllerUpdateUserRoleResponseToJSONTyped(json, false);
}

export function AdminControllerUpdateUserRoleResponseToJSONTyped(value?: AdminControllerUpdateUserRoleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'user': ModelsUserToJSON(value['user']),
    };
}

