/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthControllerResetPasswordRequest
 */
export interface AuthControllerResetPasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerResetPasswordRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof AuthControllerResetPasswordRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthControllerResetPasswordRequest
     */
    password: string;
}

/**
 * Check if a given object implements the AuthControllerResetPasswordRequest interface.
 */
export function instanceOfAuthControllerResetPasswordRequest(value: object): value is AuthControllerResetPasswordRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AuthControllerResetPasswordRequestFromJSON(json: any): AuthControllerResetPasswordRequest {
    return AuthControllerResetPasswordRequestFromJSONTyped(json, false);
}

export function AuthControllerResetPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerResetPasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function AuthControllerResetPasswordRequestToJSON(json: any): AuthControllerResetPasswordRequest {
    return AuthControllerResetPasswordRequestToJSONTyped(json, false);
}

export function AuthControllerResetPasswordRequestToJSONTyped(value?: AuthControllerResetPasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'email': value['email'],
        'password': value['password'],
    };
}

