/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthControllerDisableTOTPRequest
 */
export interface AuthControllerDisableTOTPRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerDisableTOTPRequest
     */
    code: string;
}

/**
 * Check if a given object implements the AuthControllerDisableTOTPRequest interface.
 */
export function instanceOfAuthControllerDisableTOTPRequest(value: object): value is AuthControllerDisableTOTPRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function AuthControllerDisableTOTPRequestFromJSON(json: any): AuthControllerDisableTOTPRequest {
    return AuthControllerDisableTOTPRequestFromJSONTyped(json, false);
}

export function AuthControllerDisableTOTPRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerDisableTOTPRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function AuthControllerDisableTOTPRequestToJSON(json: any): AuthControllerDisableTOTPRequest {
    return AuthControllerDisableTOTPRequestToJSONTyped(json, false);
}

export function AuthControllerDisableTOTPRequestToJSONTyped(value?: AuthControllerDisableTOTPRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

