/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthControllerRegisterRequest
 */
export interface AuthControllerRegisterRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerRegisterRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthControllerRegisterRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the AuthControllerRegisterRequest interface.
 */
export function instanceOfAuthControllerRegisterRequest(value: object): value is AuthControllerRegisterRequest {
    return true;
}

export function AuthControllerRegisterRequestFromJSON(json: any): AuthControllerRegisterRequest {
    return AuthControllerRegisterRequestFromJSONTyped(json, false);
}

export function AuthControllerRegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerRegisterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function AuthControllerRegisterRequestToJSON(json: any): AuthControllerRegisterRequest {
    return AuthControllerRegisterRequestToJSONTyped(json, false);
}

export function AuthControllerRegisterRequestToJSONTyped(value?: AuthControllerRegisterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

