/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthControllerConfirmTOTPResponse
 */
export interface AuthControllerConfirmTOTPResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerConfirmTOTPResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the AuthControllerConfirmTOTPResponse interface.
 */
export function instanceOfAuthControllerConfirmTOTPResponse(value: object): value is AuthControllerConfirmTOTPResponse {
    return true;
}

export function AuthControllerConfirmTOTPResponseFromJSON(json: any): AuthControllerConfirmTOTPResponse {
    return AuthControllerConfirmTOTPResponseFromJSONTyped(json, false);
}

export function AuthControllerConfirmTOTPResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerConfirmTOTPResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function AuthControllerConfirmTOTPResponseToJSON(json: any): AuthControllerConfirmTOTPResponse {
    return AuthControllerConfirmTOTPResponseToJSONTyped(json, false);
}

export function AuthControllerConfirmTOTPResponseToJSONTyped(value?: AuthControllerConfirmTOTPResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

