/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthControllerGetCSRFTokenResponse
 */
export interface AuthControllerGetCSRFTokenResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerGetCSRFTokenResponse
     */
    csrfToken?: string;
}

/**
 * Check if a given object implements the AuthControllerGetCSRFTokenResponse interface.
 */
export function instanceOfAuthControllerGetCSRFTokenResponse(value: object): value is AuthControllerGetCSRFTokenResponse {
    return true;
}

export function AuthControllerGetCSRFTokenResponseFromJSON(json: any): AuthControllerGetCSRFTokenResponse {
    return AuthControllerGetCSRFTokenResponseFromJSONTyped(json, false);
}

export function AuthControllerGetCSRFTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerGetCSRFTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'csrfToken': json['csrf_token'] == null ? undefined : json['csrf_token'],
    };
}

export function AuthControllerGetCSRFTokenResponseToJSON(json: any): AuthControllerGetCSRFTokenResponse {
    return AuthControllerGetCSRFTokenResponseToJSONTyped(json, false);
}

export function AuthControllerGetCSRFTokenResponseToJSONTyped(value?: AuthControllerGetCSRFTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'csrf_token': value['csrfToken'],
    };
}

