/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthControllerChangePasswordResponse
 */
export interface AuthControllerChangePasswordResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerChangePasswordResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the AuthControllerChangePasswordResponse interface.
 */
export function instanceOfAuthControllerChangePasswordResponse(value: object): value is AuthControllerChangePasswordResponse {
    return true;
}

export function AuthControllerChangePasswordResponseFromJSON(json: any): AuthControllerChangePasswordResponse {
    return AuthControllerChangePasswordResponseFromJSONTyped(json, false);
}

export function AuthControllerChangePasswordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerChangePasswordResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function AuthControllerChangePasswordResponseToJSON(json: any): AuthControllerChangePasswordResponse {
    return AuthControllerChangePasswordResponseToJSONTyped(json, false);
}

export function AuthControllerChangePasswordResponseToJSONTyped(value?: AuthControllerChangePasswordResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

