/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthControllerPasswordResetRequest
 */
export interface AuthControllerPasswordResetRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerPasswordResetRequest
     */
    email: string;
}

/**
 * Check if a given object implements the AuthControllerPasswordResetRequest interface.
 */
export function instanceOfAuthControllerPasswordResetRequest(value: object): value is AuthControllerPasswordResetRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function AuthControllerPasswordResetRequestFromJSON(json: any): AuthControllerPasswordResetRequest {
    return AuthControllerPasswordResetRequestFromJSONTyped(json, false);
}

export function AuthControllerPasswordResetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerPasswordResetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function AuthControllerPasswordResetRequestToJSON(json: any): AuthControllerPasswordResetRequest {
    return AuthControllerPasswordResetRequestToJSONTyped(json, false);
}

export function AuthControllerPasswordResetRequestToJSONTyped(value?: AuthControllerPasswordResetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

