/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthControllerLoginResponse
 */
export interface AuthControllerLoginResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerLoginResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the AuthControllerLoginResponse interface.
 */
export function instanceOfAuthControllerLoginResponse(value: object): value is AuthControllerLoginResponse {
    return true;
}

export function AuthControllerLoginResponseFromJSON(json: any): AuthControllerLoginResponse {
    return AuthControllerLoginResponseFromJSONTyped(json, false);
}

export function AuthControllerLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerLoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function AuthControllerLoginResponseToJSON(json: any): AuthControllerLoginResponse {
    return AuthControllerLoginResponseToJSONTyped(json, false);
}

export function AuthControllerLoginResponseToJSONTyped(value?: AuthControllerLoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

