/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthControllerLoginRequest
 */
export interface AuthControllerLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerLoginRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthControllerLoginRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the AuthControllerLoginRequest interface.
 */
export function instanceOfAuthControllerLoginRequest(value: object): value is AuthControllerLoginRequest {
    return true;
}

export function AuthControllerLoginRequestFromJSON(json: any): AuthControllerLoginRequest {
    return AuthControllerLoginRequestFromJSONTyped(json, false);
}

export function AuthControllerLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function AuthControllerLoginRequestToJSON(json: any): AuthControllerLoginRequest {
    return AuthControllerLoginRequestToJSONTyped(json, false);
}

export function AuthControllerLoginRequestToJSONTyped(value?: AuthControllerLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

