/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthControllerPasswordResetResponse
 */
export interface AuthControllerPasswordResetResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerPasswordResetResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the AuthControllerPasswordResetResponse interface.
 */
export function instanceOfAuthControllerPasswordResetResponse(value: object): value is AuthControllerPasswordResetResponse {
    return true;
}

export function AuthControllerPasswordResetResponseFromJSON(json: any): AuthControllerPasswordResetResponse {
    return AuthControllerPasswordResetResponseFromJSONTyped(json, false);
}

export function AuthControllerPasswordResetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerPasswordResetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function AuthControllerPasswordResetResponseToJSON(json: any): AuthControllerPasswordResetResponse {
    return AuthControllerPasswordResetResponseToJSONTyped(json, false);
}

export function AuthControllerPasswordResetResponseToJSONTyped(value?: AuthControllerPasswordResetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

