/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthControllerEnableTOTPRequest
 */
export interface AuthControllerEnableTOTPRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerEnableTOTPRequest
     */
    code: string;
}

/**
 * Check if a given object implements the AuthControllerEnableTOTPRequest interface.
 */
export function instanceOfAuthControllerEnableTOTPRequest(value: object): value is AuthControllerEnableTOTPRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function AuthControllerEnableTOTPRequestFromJSON(json: any): AuthControllerEnableTOTPRequest {
    return AuthControllerEnableTOTPRequestFromJSONTyped(json, false);
}

export function AuthControllerEnableTOTPRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerEnableTOTPRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function AuthControllerEnableTOTPRequestToJSON(json: any): AuthControllerEnableTOTPRequest {
    return AuthControllerEnableTOTPRequestToJSONTyped(json, false);
}

export function AuthControllerEnableTOTPRequestToJSONTyped(value?: AuthControllerEnableTOTPRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

