/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthControllerDisableTOTPResponse
 */
export interface AuthControllerDisableTOTPResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerDisableTOTPResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the AuthControllerDisableTOTPResponse interface.
 */
export function instanceOfAuthControllerDisableTOTPResponse(value: object): value is AuthControllerDisableTOTPResponse {
    return true;
}

export function AuthControllerDisableTOTPResponseFromJSON(json: any): AuthControllerDisableTOTPResponse {
    return AuthControllerDisableTOTPResponseFromJSONTyped(json, false);
}

export function AuthControllerDisableTOTPResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerDisableTOTPResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function AuthControllerDisableTOTPResponseToJSON(json: any): AuthControllerDisableTOTPResponse {
    return AuthControllerDisableTOTPResponseToJSONTyped(json, false);
}

export function AuthControllerDisableTOTPResponseToJSONTyped(value?: AuthControllerDisableTOTPResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

