/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsBoard } from './ModelsBoard';
import {
    ModelsBoardFromJSON,
    ModelsBoardFromJSONTyped,
    ModelsBoardToJSON,
    ModelsBoardToJSONTyped,
} from './ModelsBoard';

/**
 * 
 * @export
 * @interface BoardControllerCreateBoardResponse
 */
export interface BoardControllerCreateBoardResponse {
    /**
     * 
     * @type {ModelsBoard}
     * @memberof BoardControllerCreateBoardResponse
     */
    board?: ModelsBoard;
}

/**
 * Check if a given object implements the BoardControllerCreateBoardResponse interface.
 */
export function instanceOfBoardControllerCreateBoardResponse(value: object): value is BoardControllerCreateBoardResponse {
    return true;
}

export function BoardControllerCreateBoardResponseFromJSON(json: any): BoardControllerCreateBoardResponse {
    return BoardControllerCreateBoardResponseFromJSONTyped(json, false);
}

export function BoardControllerCreateBoardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardControllerCreateBoardResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'board': json['board'] == null ? undefined : ModelsBoardFromJSON(json['board']),
    };
}

export function BoardControllerCreateBoardResponseToJSON(json: any): BoardControllerCreateBoardResponse {
    return BoardControllerCreateBoardResponseToJSONTyped(json, false);
}

export function BoardControllerCreateBoardResponseToJSONTyped(value?: BoardControllerCreateBoardResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'board': ModelsBoardToJSON(value['board']),
    };
}

