/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BoardControllerCreateBoardRequest
 */
export interface BoardControllerCreateBoardRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof BoardControllerCreateBoardRequest
     */
    columns?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof BoardControllerCreateBoardRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof BoardControllerCreateBoardRequest
     */
    slug?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BoardControllerCreateBoardRequest
     */
    swimlanes?: Array<string>;
}

/**
 * Check if a given object implements the BoardControllerCreateBoardRequest interface.
 */
export function instanceOfBoardControllerCreateBoardRequest(value: object): value is BoardControllerCreateBoardRequest {
    return true;
}

export function BoardControllerCreateBoardRequestFromJSON(json: any): BoardControllerCreateBoardRequest {
    return BoardControllerCreateBoardRequestFromJSONTyped(json, false);
}

export function BoardControllerCreateBoardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardControllerCreateBoardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'columns': json['columns'] == null ? undefined : json['columns'],
        'name': json['name'] == null ? undefined : json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'swimlanes': json['swimlanes'] == null ? undefined : json['swimlanes'],
    };
}

export function BoardControllerCreateBoardRequestToJSON(json: any): BoardControllerCreateBoardRequest {
    return BoardControllerCreateBoardRequestToJSONTyped(json, false);
}

export function BoardControllerCreateBoardRequestToJSONTyped(value?: BoardControllerCreateBoardRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'columns': value['columns'],
        'name': value['name'],
        'slug': value['slug'],
        'swimlanes': value['swimlanes'],
    };
}

