/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BoardControllerDeleteBoardResponse
 */
export interface BoardControllerDeleteBoardResponse {
    /**
     * 
     * @type {string}
     * @memberof BoardControllerDeleteBoardResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the BoardControllerDeleteBoardResponse interface.
 */
export function instanceOfBoardControllerDeleteBoardResponse(value: object): value is BoardControllerDeleteBoardResponse {
    return true;
}

export function BoardControllerDeleteBoardResponseFromJSON(json: any): BoardControllerDeleteBoardResponse {
    return BoardControllerDeleteBoardResponseFromJSONTyped(json, false);
}

export function BoardControllerDeleteBoardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardControllerDeleteBoardResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function BoardControllerDeleteBoardResponseToJSON(json: any): BoardControllerDeleteBoardResponse {
    return BoardControllerDeleteBoardResponseToJSONTyped(json, false);
}

export function BoardControllerDeleteBoardResponseToJSONTyped(value?: BoardControllerDeleteBoardResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

