/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsBoard } from './ModelsBoard';
import {
    ModelsBoardFromJSON,
    ModelsBoardFromJSONTyped,
    ModelsBoardToJSON,
    ModelsBoardToJSONTyped,
} from './ModelsBoard';

/**
 * 
 * @export
 * @interface BoardControllerListBoardsResponse
 */
export interface BoardControllerListBoardsResponse {
    /**
     * 
     * @type {Array<ModelsBoard>}
     * @memberof BoardControllerListBoardsResponse
     */
    boards?: Array<ModelsBoard>;
}

/**
 * Check if a given object implements the BoardControllerListBoardsResponse interface.
 */
export function instanceOfBoardControllerListBoardsResponse(value: object): value is BoardControllerListBoardsResponse {
    return true;
}

export function BoardControllerListBoardsResponseFromJSON(json: any): BoardControllerListBoardsResponse {
    return BoardControllerListBoardsResponseFromJSONTyped(json, false);
}

export function BoardControllerListBoardsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardControllerListBoardsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'boards': json['boards'] == null ? undefined : ((json['boards'] as Array<any>).map(ModelsBoardFromJSON)),
    };
}

export function BoardControllerListBoardsResponseToJSON(json: any): BoardControllerListBoardsResponse {
    return BoardControllerListBoardsResponseToJSONTyped(json, false);
}

export function BoardControllerListBoardsResponseToJSONTyped(value?: BoardControllerListBoardsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'boards': value['boards'] == null ? undefined : ((value['boards'] as Array<any>).map(ModelsBoardToJSON)),
    };
}

