/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BoardControllerDeleteBoardRequest
 */
export interface BoardControllerDeleteBoardRequest {
    /**
     * 
     * @type {number}
     * @memberof BoardControllerDeleteBoardRequest
     */
    id: number;
}

/**
 * Check if a given object implements the BoardControllerDeleteBoardRequest interface.
 */
export function instanceOfBoardControllerDeleteBoardRequest(value: object): value is BoardControllerDeleteBoardRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function BoardControllerDeleteBoardRequestFromJSON(json: any): BoardControllerDeleteBoardRequest {
    return BoardControllerDeleteBoardRequestFromJSONTyped(json, false);
}

export function BoardControllerDeleteBoardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardControllerDeleteBoardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function BoardControllerDeleteBoardRequestToJSON(json: any): BoardControllerDeleteBoardRequest {
    return BoardControllerDeleteBoardRequestToJSONTyped(json, false);
}

export function BoardControllerDeleteBoardRequestToJSONTyped(value?: BoardControllerDeleteBoardRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

