/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BoardControllerGetBoardRequest
 */
export interface BoardControllerGetBoardRequest {
    /**
     * 
     * @type {number}
     * @memberof BoardControllerGetBoardRequest
     */
    id: number;
}

/**
 * Check if a given object implements the BoardControllerGetBoardRequest interface.
 */
export function instanceOfBoardControllerGetBoardRequest(value: object): value is BoardControllerGetBoardRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function BoardControllerGetBoardRequestFromJSON(json: any): BoardControllerGetBoardRequest {
    return BoardControllerGetBoardRequestFromJSONTyped(json, false);
}

export function BoardControllerGetBoardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardControllerGetBoardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function BoardControllerGetBoardRequestToJSON(json: any): BoardControllerGetBoardRequest {
    return BoardControllerGetBoardRequestToJSONTyped(json, false);
}

export function BoardControllerGetBoardRequestToJSONTyped(value?: BoardControllerGetBoardRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

