/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsBoard } from './ModelsBoard';
import {
    ModelsBoardFromJSON,
    ModelsBoardFromJSONTyped,
    ModelsBoardToJSON,
    ModelsBoardToJSONTyped,
} from './ModelsBoard';

/**
 * 
 * @export
 * @interface BoardControllerGetBoardResponse
 */
export interface BoardControllerGetBoardResponse {
    /**
     * 
     * @type {ModelsBoard}
     * @memberof BoardControllerGetBoardResponse
     */
    board?: ModelsBoard;
}

/**
 * Check if a given object implements the BoardControllerGetBoardResponse interface.
 */
export function instanceOfBoardControllerGetBoardResponse(value: object): value is BoardControllerGetBoardResponse {
    return true;
}

export function BoardControllerGetBoardResponseFromJSON(json: any): BoardControllerGetBoardResponse {
    return BoardControllerGetBoardResponseFromJSONTyped(json, false);
}

export function BoardControllerGetBoardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardControllerGetBoardResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'board': json['board'] == null ? undefined : ModelsBoardFromJSON(json['board']),
    };
}

export function BoardControllerGetBoardResponseToJSON(json: any): BoardControllerGetBoardResponse {
    return BoardControllerGetBoardResponseToJSONTyped(json, false);
}

export function BoardControllerGetBoardResponseToJSONTyped(value?: BoardControllerGetBoardResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'board': ModelsBoardToJSON(value['board']),
    };
}

