/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsBoard } from './ModelsBoard';
import {
    ModelsBoardFromJSON,
    ModelsBoardFromJSONTyped,
    ModelsBoardToJSON,
    ModelsBoardToJSONTyped,
} from './ModelsBoard';

/**
 * 
 * @export
 * @interface BoardControllerGetBoardBySlugResponse
 */
export interface BoardControllerGetBoardBySlugResponse {
    /**
     * 
     * @type {ModelsBoard}
     * @memberof BoardControllerGetBoardBySlugResponse
     */
    board?: ModelsBoard;
}

/**
 * Check if a given object implements the BoardControllerGetBoardBySlugResponse interface.
 */
export function instanceOfBoardControllerGetBoardBySlugResponse(value: object): value is BoardControllerGetBoardBySlugResponse {
    return true;
}

export function BoardControllerGetBoardBySlugResponseFromJSON(json: any): BoardControllerGetBoardBySlugResponse {
    return BoardControllerGetBoardBySlugResponseFromJSONTyped(json, false);
}

export function BoardControllerGetBoardBySlugResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardControllerGetBoardBySlugResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'board': json['board'] == null ? undefined : ModelsBoardFromJSON(json['board']),
    };
}

export function BoardControllerGetBoardBySlugResponseToJSON(json: any): BoardControllerGetBoardBySlugResponse {
    return BoardControllerGetBoardBySlugResponseToJSONTyped(json, false);
}

export function BoardControllerGetBoardBySlugResponseToJSONTyped(value?: BoardControllerGetBoardBySlugResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'board': ModelsBoardToJSON(value['board']),
    };
}

