/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ColumnControllerEditColumnRequest
 */
export interface ColumnControllerEditColumnRequest {
    /**
     * 
     * @type {number}
     * @memberof ColumnControllerEditColumnRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ColumnControllerEditColumnRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the ColumnControllerEditColumnRequest interface.
 */
export function instanceOfColumnControllerEditColumnRequest(value: object): value is ColumnControllerEditColumnRequest {
    return true;
}

export function ColumnControllerEditColumnRequestFromJSON(json: any): ColumnControllerEditColumnRequest {
    return ColumnControllerEditColumnRequestFromJSONTyped(json, false);
}

export function ColumnControllerEditColumnRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnControllerEditColumnRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ColumnControllerEditColumnRequestToJSON(json: any): ColumnControllerEditColumnRequest {
    return ColumnControllerEditColumnRequestToJSONTyped(json, false);
}

export function ColumnControllerEditColumnRequestToJSONTyped(value?: ColumnControllerEditColumnRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

