/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsColumn } from './ModelsColumn';
import {
    ModelsColumnFromJSON,
    ModelsColumnFromJSONTyped,
    ModelsColumnToJSON,
    ModelsColumnToJSONTyped,
} from './ModelsColumn';

/**
 * 
 * @export
 * @interface ColumnControllerCreateColumnResponse
 */
export interface ColumnControllerCreateColumnResponse {
    /**
     * 
     * @type {ModelsColumn}
     * @memberof ColumnControllerCreateColumnResponse
     */
    column?: ModelsColumn;
}

/**
 * Check if a given object implements the ColumnControllerCreateColumnResponse interface.
 */
export function instanceOfColumnControllerCreateColumnResponse(value: object): value is ColumnControllerCreateColumnResponse {
    return true;
}

export function ColumnControllerCreateColumnResponseFromJSON(json: any): ColumnControllerCreateColumnResponse {
    return ColumnControllerCreateColumnResponseFromJSONTyped(json, false);
}

export function ColumnControllerCreateColumnResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnControllerCreateColumnResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'column': json['column'] == null ? undefined : ModelsColumnFromJSON(json['column']),
    };
}

export function ColumnControllerCreateColumnResponseToJSON(json: any): ColumnControllerCreateColumnResponse {
    return ColumnControllerCreateColumnResponseToJSONTyped(json, false);
}

export function ColumnControllerCreateColumnResponseToJSONTyped(value?: ColumnControllerCreateColumnResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'column': ModelsColumnToJSON(value['column']),
    };
}

