/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ColumnControllerCreateColumnRequest
 */
export interface ColumnControllerCreateColumnRequest {
    /**
     * 
     * @type {number}
     * @memberof ColumnControllerCreateColumnRequest
     */
    boardId?: number;
    /**
     * 
     * @type {string}
     * @memberof ColumnControllerCreateColumnRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the ColumnControllerCreateColumnRequest interface.
 */
export function instanceOfColumnControllerCreateColumnRequest(value: object): value is ColumnControllerCreateColumnRequest {
    return true;
}

export function ColumnControllerCreateColumnRequestFromJSON(json: any): ColumnControllerCreateColumnRequest {
    return ColumnControllerCreateColumnRequestFromJSONTyped(json, false);
}

export function ColumnControllerCreateColumnRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnControllerCreateColumnRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'boardId': json['board_id'] == null ? undefined : json['board_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ColumnControllerCreateColumnRequestToJSON(json: any): ColumnControllerCreateColumnRequest {
    return ColumnControllerCreateColumnRequestToJSONTyped(json, false);
}

export function ColumnControllerCreateColumnRequestToJSONTyped(value?: ColumnControllerCreateColumnRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'board_id': value['boardId'],
        'name': value['name'],
    };
}

