/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsColumn } from './ModelsColumn';
import {
    ModelsColumnFromJSON,
    ModelsColumnFromJSONTyped,
    ModelsColumnToJSON,
    ModelsColumnToJSONTyped,
} from './ModelsColumn';

/**
 * 
 * @export
 * @interface ColumnControllerMoveColumnResponse
 */
export interface ColumnControllerMoveColumnResponse {
    /**
     * 
     * @type {ModelsColumn}
     * @memberof ColumnControllerMoveColumnResponse
     */
    column?: ModelsColumn;
}

/**
 * Check if a given object implements the ColumnControllerMoveColumnResponse interface.
 */
export function instanceOfColumnControllerMoveColumnResponse(value: object): value is ColumnControllerMoveColumnResponse {
    return true;
}

export function ColumnControllerMoveColumnResponseFromJSON(json: any): ColumnControllerMoveColumnResponse {
    return ColumnControllerMoveColumnResponseFromJSONTyped(json, false);
}

export function ColumnControllerMoveColumnResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnControllerMoveColumnResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'column': json['column'] == null ? undefined : ModelsColumnFromJSON(json['column']),
    };
}

export function ColumnControllerMoveColumnResponseToJSON(json: any): ColumnControllerMoveColumnResponse {
    return ColumnControllerMoveColumnResponseToJSONTyped(json, false);
}

export function ColumnControllerMoveColumnResponseToJSONTyped(value?: ColumnControllerMoveColumnResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'column': ModelsColumnToJSON(value['column']),
    };
}

