/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsColumn } from './ModelsColumn';
import {
    ModelsColumnFromJSON,
    ModelsColumnFromJSONTyped,
    ModelsColumnToJSON,
    ModelsColumnToJSONTyped,
} from './ModelsColumn';

/**
 * 
 * @export
 * @interface ColumnControllerDeleteColumnResponse
 */
export interface ColumnControllerDeleteColumnResponse {
    /**
     * 
     * @type {ModelsColumn}
     * @memberof ColumnControllerDeleteColumnResponse
     */
    column?: ModelsColumn;
}

/**
 * Check if a given object implements the ColumnControllerDeleteColumnResponse interface.
 */
export function instanceOfColumnControllerDeleteColumnResponse(value: object): value is ColumnControllerDeleteColumnResponse {
    return true;
}

export function ColumnControllerDeleteColumnResponseFromJSON(json: any): ColumnControllerDeleteColumnResponse {
    return ColumnControllerDeleteColumnResponseFromJSONTyped(json, false);
}

export function ColumnControllerDeleteColumnResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnControllerDeleteColumnResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'column': json['column'] == null ? undefined : ModelsColumnFromJSON(json['column']),
    };
}

export function ColumnControllerDeleteColumnResponseToJSON(json: any): ColumnControllerDeleteColumnResponse {
    return ColumnControllerDeleteColumnResponseToJSONTyped(json, false);
}

export function ColumnControllerDeleteColumnResponseToJSONTyped(value?: ColumnControllerDeleteColumnResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'column': ModelsColumnToJSON(value['column']),
    };
}

