/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsColumn } from './ModelsColumn';
import {
    ModelsColumnFromJSON,
    ModelsColumnFromJSONTyped,
    ModelsColumnToJSON,
    ModelsColumnToJSONTyped,
} from './ModelsColumn';

/**
 * 
 * @export
 * @interface ColumnControllerEditColumnResponse
 */
export interface ColumnControllerEditColumnResponse {
    /**
     * 
     * @type {ModelsColumn}
     * @memberof ColumnControllerEditColumnResponse
     */
    column?: ModelsColumn;
}

/**
 * Check if a given object implements the ColumnControllerEditColumnResponse interface.
 */
export function instanceOfColumnControllerEditColumnResponse(value: object): value is ColumnControllerEditColumnResponse {
    return true;
}

export function ColumnControllerEditColumnResponseFromJSON(json: any): ColumnControllerEditColumnResponse {
    return ColumnControllerEditColumnResponseFromJSONTyped(json, false);
}

export function ColumnControllerEditColumnResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnControllerEditColumnResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'column': json['column'] == null ? undefined : ModelsColumnFromJSON(json['column']),
    };
}

export function ColumnControllerEditColumnResponseToJSON(json: any): ColumnControllerEditColumnResponse {
    return ColumnControllerEditColumnResponseToJSONTyped(json, false);
}

export function ColumnControllerEditColumnResponseToJSONTyped(value?: ColumnControllerEditColumnResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'column': ModelsColumnToJSON(value['column']),
    };
}

