/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsComment } from './ModelsComment';
import {
    ModelsCommentFromJSON,
    ModelsCommentFromJSONTyped,
    ModelsCommentToJSON,
    ModelsCommentToJSONTyped,
} from './ModelsComment';

/**
 * 
 * @export
 * @interface CommentControllerDeleteCommentResponse
 */
export interface CommentControllerDeleteCommentResponse {
    /**
     * 
     * @type {ModelsComment}
     * @memberof CommentControllerDeleteCommentResponse
     */
    comment?: ModelsComment;
}

/**
 * Check if a given object implements the CommentControllerDeleteCommentResponse interface.
 */
export function instanceOfCommentControllerDeleteCommentResponse(value: object): value is CommentControllerDeleteCommentResponse {
    return true;
}

export function CommentControllerDeleteCommentResponseFromJSON(json: any): CommentControllerDeleteCommentResponse {
    return CommentControllerDeleteCommentResponseFromJSONTyped(json, false);
}

export function CommentControllerDeleteCommentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentControllerDeleteCommentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'] == null ? undefined : ModelsCommentFromJSON(json['comment']),
    };
}

export function CommentControllerDeleteCommentResponseToJSON(json: any): CommentControllerDeleteCommentResponse {
    return CommentControllerDeleteCommentResponseToJSONTyped(json, false);
}

export function CommentControllerDeleteCommentResponseToJSONTyped(value?: CommentControllerDeleteCommentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment': ModelsCommentToJSON(value['comment']),
    };
}

