/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsComment } from './ModelsComment';
import {
    ModelsCommentFromJSON,
    ModelsCommentFromJSONTyped,
    ModelsCommentToJSON,
    ModelsCommentToJSONTyped,
} from './ModelsComment';

/**
 * 
 * @export
 * @interface CommentControllerEditCommentResponse
 */
export interface CommentControllerEditCommentResponse {
    /**
     * 
     * @type {ModelsComment}
     * @memberof CommentControllerEditCommentResponse
     */
    comment?: ModelsComment;
}

/**
 * Check if a given object implements the CommentControllerEditCommentResponse interface.
 */
export function instanceOfCommentControllerEditCommentResponse(value: object): value is CommentControllerEditCommentResponse {
    return true;
}

export function CommentControllerEditCommentResponseFromJSON(json: any): CommentControllerEditCommentResponse {
    return CommentControllerEditCommentResponseFromJSONTyped(json, false);
}

export function CommentControllerEditCommentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentControllerEditCommentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'] == null ? undefined : ModelsCommentFromJSON(json['comment']),
    };
}

export function CommentControllerEditCommentResponseToJSON(json: any): CommentControllerEditCommentResponse {
    return CommentControllerEditCommentResponseToJSONTyped(json, false);
}

export function CommentControllerEditCommentResponseToJSONTyped(value?: CommentControllerEditCommentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment': ModelsCommentToJSON(value['comment']),
    };
}

