/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsComment } from './ModelsComment';
import {
    ModelsCommentFromJSON,
    ModelsCommentFromJSONTyped,
    ModelsCommentToJSON,
    ModelsCommentToJSONTyped,
} from './ModelsComment';

/**
 * 
 * @export
 * @interface CommentControllerCreateCommentResponse
 */
export interface CommentControllerCreateCommentResponse {
    /**
     * 
     * @type {ModelsComment}
     * @memberof CommentControllerCreateCommentResponse
     */
    comment?: ModelsComment;
}

/**
 * Check if a given object implements the CommentControllerCreateCommentResponse interface.
 */
export function instanceOfCommentControllerCreateCommentResponse(value: object): value is CommentControllerCreateCommentResponse {
    return true;
}

export function CommentControllerCreateCommentResponseFromJSON(json: any): CommentControllerCreateCommentResponse {
    return CommentControllerCreateCommentResponseFromJSONTyped(json, false);
}

export function CommentControllerCreateCommentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentControllerCreateCommentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'] == null ? undefined : ModelsCommentFromJSON(json['comment']),
    };
}

export function CommentControllerCreateCommentResponseToJSON(json: any): CommentControllerCreateCommentResponse {
    return CommentControllerCreateCommentResponseToJSONTyped(json, false);
}

export function CommentControllerCreateCommentResponseToJSONTyped(value?: CommentControllerCreateCommentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment': ModelsCommentToJSON(value['comment']),
    };
}

