/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentControllerDeleteCommentRequest
 */
export interface CommentControllerDeleteCommentRequest {
    /**
     * 
     * @type {number}
     * @memberof CommentControllerDeleteCommentRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the CommentControllerDeleteCommentRequest interface.
 */
export function instanceOfCommentControllerDeleteCommentRequest(value: object): value is CommentControllerDeleteCommentRequest {
    return true;
}

export function CommentControllerDeleteCommentRequestFromJSON(json: any): CommentControllerDeleteCommentRequest {
    return CommentControllerDeleteCommentRequestFromJSONTyped(json, false);
}

export function CommentControllerDeleteCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentControllerDeleteCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function CommentControllerDeleteCommentRequestToJSON(json: any): CommentControllerDeleteCommentRequest {
    return CommentControllerDeleteCommentRequestToJSONTyped(json, false);
}

export function CommentControllerDeleteCommentRequestToJSONTyped(value?: CommentControllerDeleteCommentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

