/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentControllerEditCommentRequest
 */
export interface CommentControllerEditCommentRequest {
    /**
     * 
     * @type {number}
     * @memberof CommentControllerEditCommentRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CommentControllerEditCommentRequest
     */
    text?: string;
}

/**
 * Check if a given object implements the CommentControllerEditCommentRequest interface.
 */
export function instanceOfCommentControllerEditCommentRequest(value: object): value is CommentControllerEditCommentRequest {
    return true;
}

export function CommentControllerEditCommentRequestFromJSON(json: any): CommentControllerEditCommentRequest {
    return CommentControllerEditCommentRequestFromJSONTyped(json, false);
}

export function CommentControllerEditCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentControllerEditCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function CommentControllerEditCommentRequestToJSON(json: any): CommentControllerEditCommentRequest {
    return CommentControllerEditCommentRequestToJSONTyped(json, false);
}

export function CommentControllerEditCommentRequestToJSONTyped(value?: CommentControllerEditCommentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'text': value['text'],
    };
}

