/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentControllerCreateCommentRequest
 */
export interface CommentControllerCreateCommentRequest {
    /**
     * 
     * @type {number}
     * @memberof CommentControllerCreateCommentRequest
     */
    taskId?: number;
    /**
     * 
     * @type {string}
     * @memberof CommentControllerCreateCommentRequest
     */
    text?: string;
}

/**
 * Check if a given object implements the CommentControllerCreateCommentRequest interface.
 */
export function instanceOfCommentControllerCreateCommentRequest(value: object): value is CommentControllerCreateCommentRequest {
    return true;
}

export function CommentControllerCreateCommentRequestFromJSON(json: any): CommentControllerCreateCommentRequest {
    return CommentControllerCreateCommentRequestFromJSONTyped(json, false);
}

export function CommentControllerCreateCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentControllerCreateCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function CommentControllerCreateCommentRequestToJSON(json: any): CommentControllerCreateCommentRequest {
    return CommentControllerCreateCommentRequestToJSONTyped(json, false);
}

export function CommentControllerCreateCommentRequestToJSONTyped(value?: CommentControllerCreateCommentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task_id': value['taskId'],
        'text': value['text'],
    };
}

