/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MiscControllerAppNameResponse
 */
export interface MiscControllerAppNameResponse {
    /**
     * 
     * @type {string}
     * @memberof MiscControllerAppNameResponse
     */
    appName?: string;
}

/**
 * Check if a given object implements the MiscControllerAppNameResponse interface.
 */
export function instanceOfMiscControllerAppNameResponse(value: object): value is MiscControllerAppNameResponse {
    return true;
}

export function MiscControllerAppNameResponseFromJSON(json: any): MiscControllerAppNameResponse {
    return MiscControllerAppNameResponseFromJSONTyped(json, false);
}

export function MiscControllerAppNameResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MiscControllerAppNameResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appName': json['app_name'] == null ? undefined : json['app_name'],
    };
}

export function MiscControllerAppNameResponseToJSON(json: any): MiscControllerAppNameResponse {
    return MiscControllerAppNameResponseToJSONTyped(json, false);
}

export function MiscControllerAppNameResponseToJSONTyped(value?: MiscControllerAppNameResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_name': value['appName'],
    };
}

