/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GormDeletedAt } from './GormDeletedAt';
import {
    GormDeletedAtFromJSON,
    GormDeletedAtFromJSONTyped,
    GormDeletedAtToJSON,
    GormDeletedAtToJSONTyped,
} from './GormDeletedAt';
import type { ModelsUser } from './ModelsUser';
import {
    ModelsUserFromJSON,
    ModelsUserFromJSONTyped,
    ModelsUserToJSON,
    ModelsUserToJSONTyped,
} from './ModelsUser';

/**
 * 
 * @export
 * @interface ModelsBoardPermission
 */
export interface ModelsBoardPermission {
    /**
     * 
     * @type {number}
     * @memberof ModelsBoardPermission
     */
    boardId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsBoardPermission
     */
    createdAt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsBoardPermission
     */
    _delete?: boolean;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof ModelsBoardPermission
     */
    deletedAt?: GormDeletedAt;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsBoardPermission
     */
    edit?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsBoardPermission
     */
    generalAccess?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ModelsBoardPermission
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsBoardPermission
     */
    updatedAt?: string;
    /**
     * 
     * @type {ModelsUser}
     * @memberof ModelsBoardPermission
     */
    user?: ModelsUser;
    /**
     * 
     * @type {number}
     * @memberof ModelsBoardPermission
     */
    userId?: number;
}

/**
 * Check if a given object implements the ModelsBoardPermission interface.
 */
export function instanceOfModelsBoardPermission(value: object): value is ModelsBoardPermission {
    return true;
}

export function ModelsBoardPermissionFromJSON(json: any): ModelsBoardPermission {
    return ModelsBoardPermissionFromJSONTyped(json, false);
}

export function ModelsBoardPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsBoardPermission {
    if (json == null) {
        return json;
    }
    return {
        
        'boardId': json['board_id'] == null ? undefined : json['board_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        '_delete': json['delete'] == null ? undefined : json['delete'],
        'deletedAt': json['deleted_at'] == null ? undefined : GormDeletedAtFromJSON(json['deleted_at']),
        'edit': json['edit'] == null ? undefined : json['edit'],
        'generalAccess': json['general_access'] == null ? undefined : json['general_access'],
        'id': json['id'] == null ? undefined : json['id'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'user': json['user'] == null ? undefined : ModelsUserFromJSON(json['user']),
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function ModelsBoardPermissionToJSON(json: any): ModelsBoardPermission {
    return ModelsBoardPermissionToJSONTyped(json, false);
}

export function ModelsBoardPermissionToJSONTyped(value?: ModelsBoardPermission | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'board_id': value['boardId'],
        'created_at': value['createdAt'],
        'delete': value['_delete'],
        'deleted_at': GormDeletedAtToJSON(value['deletedAt']),
        'edit': value['edit'],
        'general_access': value['generalAccess'],
        'id': value['id'],
        'updated_at': value['updatedAt'],
        'user': ModelsUserToJSON(value['user']),
        'user_id': value['userId'],
    };
}

