/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GormDeletedAt } from './GormDeletedAt';
import {
    GormDeletedAtFromJSON,
    GormDeletedAtFromJSONTyped,
    GormDeletedAtToJSON,
    GormDeletedAtToJSONTyped,
} from './GormDeletedAt';

/**
 * 
 * @export
 * @interface ModelsColumn
 */
export interface ModelsColumn {
    /**
     * 
     * @type {number}
     * @memberof ModelsColumn
     */
    boardId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsColumn
     */
    createdAt?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof ModelsColumn
     */
    deletedAt?: GormDeletedAt;
    /**
     * 
     * @type {number}
     * @memberof ModelsColumn
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsColumn
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsColumn
     */
    order?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsColumn
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the ModelsColumn interface.
 */
export function instanceOfModelsColumn(value: object): value is ModelsColumn {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ModelsColumnFromJSON(json: any): ModelsColumn {
    return ModelsColumnFromJSONTyped(json, false);
}

export function ModelsColumnFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsColumn {
    if (json == null) {
        return json;
    }
    return {
        
        'boardId': json['board_id'] == null ? undefined : json['board_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'deletedAt': json['deleted_at'] == null ? undefined : GormDeletedAtFromJSON(json['deleted_at']),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'order': json['order'] == null ? undefined : json['order'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function ModelsColumnToJSON(json: any): ModelsColumn {
    return ModelsColumnToJSONTyped(json, false);
}

export function ModelsColumnToJSONTyped(value?: ModelsColumn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'board_id': value['boardId'],
        'created_at': value['createdAt'],
        'deleted_at': GormDeletedAtToJSON(value['deletedAt']),
        'id': value['id'],
        'name': value['name'],
        'order': value['order'],
        'updated_at': value['updatedAt'],
    };
}

