/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GormDeletedAt } from './GormDeletedAt';
import {
    GormDeletedAtFromJSON,
    GormDeletedAtFromJSONTyped,
    GormDeletedAtToJSON,
    GormDeletedAtToJSONTyped,
} from './GormDeletedAt';
import type { ModelsUser } from './ModelsUser';
import {
    ModelsUserFromJSON,
    ModelsUserFromJSONTyped,
    ModelsUserToJSON,
    ModelsUserToJSONTyped,
} from './ModelsUser';
import type { ModelsComment } from './ModelsComment';
import {
    ModelsCommentFromJSON,
    ModelsCommentFromJSONTyped,
    ModelsCommentToJSON,
    ModelsCommentToJSONTyped,
} from './ModelsComment';
import type { ModelsColumn } from './ModelsColumn';
import {
    ModelsColumnFromJSON,
    ModelsColumnFromJSONTyped,
    ModelsColumnToJSON,
    ModelsColumnToJSONTyped,
} from './ModelsColumn';
import type { ModelsSwimlane } from './ModelsSwimlane';
import {
    ModelsSwimlaneFromJSON,
    ModelsSwimlaneFromJSONTyped,
    ModelsSwimlaneToJSON,
    ModelsSwimlaneToJSONTyped,
} from './ModelsSwimlane';

/**
 * 
 * @export
 * @interface ModelsTask
 */
export interface ModelsTask {
    /**
     * 
     * @type {ModelsUser}
     * @memberof ModelsTask
     */
    assignee?: ModelsUser;
    /**
     * 
     * @type {number}
     * @memberof ModelsTask
     */
    assigneeId?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsTask
     */
    boardId?: number;
    /**
     * 
     * @type {ModelsColumn}
     * @memberof ModelsTask
     */
    column?: ModelsColumn;
    /**
     * 
     * @type {number}
     * @memberof ModelsTask
     */
    columnId?: number;
    /**
     * 
     * @type {Array<ModelsComment>}
     * @memberof ModelsTask
     */
    comments?: Array<ModelsComment>;
    /**
     * 
     * @type {string}
     * @memberof ModelsTask
     */
    createdAt?: string;
    /**
     * 
     * @type {ModelsUser}
     * @memberof ModelsTask
     */
    creator?: ModelsUser;
    /**
     * 
     * @type {number}
     * @memberof ModelsTask
     */
    creatorId?: number;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof ModelsTask
     */
    deletedAt?: GormDeletedAt;
    /**
     * 
     * @type {string}
     * @memberof ModelsTask
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsTask
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsTask
     */
    position?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsTask
     */
    status?: string;
    /**
     * 
     * @type {ModelsSwimlane}
     * @memberof ModelsTask
     */
    swimlane?: ModelsSwimlane;
    /**
     * 
     * @type {number}
     * @memberof ModelsTask
     */
    swimlaneId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsTask
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTask
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the ModelsTask interface.
 */
export function instanceOfModelsTask(value: object): value is ModelsTask {
    return true;
}

export function ModelsTaskFromJSON(json: any): ModelsTask {
    return ModelsTaskFromJSONTyped(json, false);
}

export function ModelsTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsTask {
    if (json == null) {
        return json;
    }
    return {
        
        'assignee': json['assignee'] == null ? undefined : ModelsUserFromJSON(json['assignee']),
        'assigneeId': json['assignee_id'] == null ? undefined : json['assignee_id'],
        'boardId': json['board_id'] == null ? undefined : json['board_id'],
        'column': json['column'] == null ? undefined : ModelsColumnFromJSON(json['column']),
        'columnId': json['column_id'] == null ? undefined : json['column_id'],
        'comments': json['comments'] == null ? undefined : ((json['comments'] as Array<any>).map(ModelsCommentFromJSON)),
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'creator': json['creator'] == null ? undefined : ModelsUserFromJSON(json['creator']),
        'creatorId': json['creator_id'] == null ? undefined : json['creator_id'],
        'deletedAt': json['deleted_at'] == null ? undefined : GormDeletedAtFromJSON(json['deleted_at']),
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'position': json['position'] == null ? undefined : json['position'],
        'status': json['status'] == null ? undefined : json['status'],
        'swimlane': json['swimlane'] == null ? undefined : ModelsSwimlaneFromJSON(json['swimlane']),
        'swimlaneId': json['swimlane_id'] == null ? undefined : json['swimlane_id'],
        'title': json['title'] == null ? undefined : json['title'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function ModelsTaskToJSON(json: any): ModelsTask {
    return ModelsTaskToJSONTyped(json, false);
}

export function ModelsTaskToJSONTyped(value?: ModelsTask | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assignee': ModelsUserToJSON(value['assignee']),
        'assignee_id': value['assigneeId'],
        'board_id': value['boardId'],
        'column': ModelsColumnToJSON(value['column']),
        'column_id': value['columnId'],
        'comments': value['comments'] == null ? undefined : ((value['comments'] as Array<any>).map(ModelsCommentToJSON)),
        'created_at': value['createdAt'],
        'creator': ModelsUserToJSON(value['creator']),
        'creator_id': value['creatorId'],
        'deleted_at': GormDeletedAtToJSON(value['deletedAt']),
        'description': value['description'],
        'id': value['id'],
        'position': value['position'],
        'status': value['status'],
        'swimlane': ModelsSwimlaneToJSON(value['swimlane']),
        'swimlane_id': value['swimlaneId'],
        'title': value['title'],
        'updated_at': value['updatedAt'],
    };
}

