/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GormDeletedAt } from './GormDeletedAt';
import {
    GormDeletedAtFromJSON,
    GormDeletedAtFromJSONTyped,
    GormDeletedAtToJSON,
    GormDeletedAtToJSONTyped,
} from './GormDeletedAt';
import type { ModelsUser } from './ModelsUser';
import {
    ModelsUserFromJSON,
    ModelsUserFromJSONTyped,
    ModelsUserToJSON,
    ModelsUserToJSONTyped,
} from './ModelsUser';
import type { ModelsColumn } from './ModelsColumn';
import {
    ModelsColumnFromJSON,
    ModelsColumnFromJSONTyped,
    ModelsColumnToJSON,
    ModelsColumnToJSONTyped,
} from './ModelsColumn';
import type { ModelsSwimlane } from './ModelsSwimlane';
import {
    ModelsSwimlaneFromJSON,
    ModelsSwimlaneFromJSONTyped,
    ModelsSwimlaneToJSON,
    ModelsSwimlaneToJSONTyped,
} from './ModelsSwimlane';
import type { ModelsTask } from './ModelsTask';
import {
    ModelsTaskFromJSON,
    ModelsTaskFromJSONTyped,
    ModelsTaskToJSON,
    ModelsTaskToJSONTyped,
} from './ModelsTask';
import type { ModelsBoardPermission } from './ModelsBoardPermission';
import {
    ModelsBoardPermissionFromJSON,
    ModelsBoardPermissionFromJSONTyped,
    ModelsBoardPermissionToJSON,
    ModelsBoardPermissionToJSONTyped,
} from './ModelsBoardPermission';

/**
 * 
 * @export
 * @interface ModelsBoard
 */
export interface ModelsBoard {
    /**
     * 
     * @type {Array<ModelsColumn>}
     * @memberof ModelsBoard
     */
    columns?: Array<ModelsColumn>;
    /**
     * 
     * @type {string}
     * @memberof ModelsBoard
     */
    createdAt?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof ModelsBoard
     */
    deletedAt?: GormDeletedAt;
    /**
     * 
     * @type {number}
     * @memberof ModelsBoard
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsBoard
     */
    name: string;
    /**
     * 
     * @type {ModelsUser}
     * @memberof ModelsBoard
     */
    owner?: ModelsUser;
    /**
     * 
     * @type {number}
     * @memberof ModelsBoard
     */
    ownerId?: number;
    /**
     * 
     * @type {Array<ModelsBoardPermission>}
     * @memberof ModelsBoard
     */
    permissions?: Array<ModelsBoardPermission>;
    /**
     * 
     * @type {Array<ModelsSwimlane>}
     * @memberof ModelsBoard
     */
    swimlanes?: Array<ModelsSwimlane>;
    /**
     * 
     * @type {Array<ModelsTask>}
     * @memberof ModelsBoard
     */
    tasks?: Array<ModelsTask>;
    /**
     * 
     * @type {string}
     * @memberof ModelsBoard
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the ModelsBoard interface.
 */
export function instanceOfModelsBoard(value: object): value is ModelsBoard {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ModelsBoardFromJSON(json: any): ModelsBoard {
    return ModelsBoardFromJSONTyped(json, false);
}

export function ModelsBoardFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsBoard {
    if (json == null) {
        return json;
    }
    return {
        
        'columns': json['columns'] == null ? undefined : ((json['columns'] as Array<any>).map(ModelsColumnFromJSON)),
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'deletedAt': json['deleted_at'] == null ? undefined : GormDeletedAtFromJSON(json['deleted_at']),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'owner': json['owner'] == null ? undefined : ModelsUserFromJSON(json['owner']),
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
        'permissions': json['permissions'] == null ? undefined : ((json['permissions'] as Array<any>).map(ModelsBoardPermissionFromJSON)),
        'swimlanes': json['swimlanes'] == null ? undefined : ((json['swimlanes'] as Array<any>).map(ModelsSwimlaneFromJSON)),
        'tasks': json['tasks'] == null ? undefined : ((json['tasks'] as Array<any>).map(ModelsTaskFromJSON)),
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function ModelsBoardToJSON(json: any): ModelsBoard {
    return ModelsBoardToJSONTyped(json, false);
}

export function ModelsBoardToJSONTyped(value?: ModelsBoard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'columns': value['columns'] == null ? undefined : ((value['columns'] as Array<any>).map(ModelsColumnToJSON)),
        'created_at': value['createdAt'],
        'deleted_at': GormDeletedAtToJSON(value['deletedAt']),
        'id': value['id'],
        'name': value['name'],
        'owner': ModelsUserToJSON(value['owner']),
        'owner_id': value['ownerId'],
        'permissions': value['permissions'] == null ? undefined : ((value['permissions'] as Array<any>).map(ModelsBoardPermissionToJSON)),
        'swimlanes': value['swimlanes'] == null ? undefined : ((value['swimlanes'] as Array<any>).map(ModelsSwimlaneToJSON)),
        'tasks': value['tasks'] == null ? undefined : ((value['tasks'] as Array<any>).map(ModelsTaskToJSON)),
        'updated_at': value['updatedAt'],
    };
}

