/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SampleDataControllerInsertSampleDataRequest
 */
export interface SampleDataControllerInsertSampleDataRequest {
    /**
     * 
     * @type {number}
     * @memberof SampleDataControllerInsertSampleDataRequest
     */
    boardId?: number;
    /**
     * 
     * @type {number}
     * @memberof SampleDataControllerInsertSampleDataRequest
     */
    numTasks?: number;
}

/**
 * Check if a given object implements the SampleDataControllerInsertSampleDataRequest interface.
 */
export function instanceOfSampleDataControllerInsertSampleDataRequest(value: object): value is SampleDataControllerInsertSampleDataRequest {
    return true;
}

export function SampleDataControllerInsertSampleDataRequestFromJSON(json: any): SampleDataControllerInsertSampleDataRequest {
    return SampleDataControllerInsertSampleDataRequestFromJSONTyped(json, false);
}

export function SampleDataControllerInsertSampleDataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SampleDataControllerInsertSampleDataRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'boardId': json['board_id'] == null ? undefined : json['board_id'],
        'numTasks': json['num_tasks'] == null ? undefined : json['num_tasks'],
    };
}

export function SampleDataControllerInsertSampleDataRequestToJSON(json: any): SampleDataControllerInsertSampleDataRequest {
    return SampleDataControllerInsertSampleDataRequestToJSONTyped(json, false);
}

export function SampleDataControllerInsertSampleDataRequestToJSONTyped(value?: SampleDataControllerInsertSampleDataRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'board_id': value['boardId'],
        'num_tasks': value['numTasks'],
    };
}

