/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SampleDataControllerInsertSampleDataResponse
 */
export interface SampleDataControllerInsertSampleDataResponse {
    /**
     * 
     * @type {string}
     * @memberof SampleDataControllerInsertSampleDataResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the SampleDataControllerInsertSampleDataResponse interface.
 */
export function instanceOfSampleDataControllerInsertSampleDataResponse(value: object): value is SampleDataControllerInsertSampleDataResponse {
    return true;
}

export function SampleDataControllerInsertSampleDataResponseFromJSON(json: any): SampleDataControllerInsertSampleDataResponse {
    return SampleDataControllerInsertSampleDataResponseFromJSONTyped(json, false);
}

export function SampleDataControllerInsertSampleDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SampleDataControllerInsertSampleDataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function SampleDataControllerInsertSampleDataResponseToJSON(json: any): SampleDataControllerInsertSampleDataResponse {
    return SampleDataControllerInsertSampleDataResponseToJSONTyped(json, false);
}

export function SampleDataControllerInsertSampleDataResponseToJSONTyped(value?: SampleDataControllerInsertSampleDataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

