/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsSwimlane } from './ModelsSwimlane';
import {
    ModelsSwimlaneFromJSON,
    ModelsSwimlaneFromJSONTyped,
    ModelsSwimlaneToJSON,
    ModelsSwimlaneToJSONTyped,
} from './ModelsSwimlane';

/**
 * 
 * @export
 * @interface SwimlaneControllerDeleteSwimlaneResponse
 */
export interface SwimlaneControllerDeleteSwimlaneResponse {
    /**
     * 
     * @type {ModelsSwimlane}
     * @memberof SwimlaneControllerDeleteSwimlaneResponse
     */
    swimlane?: ModelsSwimlane;
}

/**
 * Check if a given object implements the SwimlaneControllerDeleteSwimlaneResponse interface.
 */
export function instanceOfSwimlaneControllerDeleteSwimlaneResponse(value: object): value is SwimlaneControllerDeleteSwimlaneResponse {
    return true;
}

export function SwimlaneControllerDeleteSwimlaneResponseFromJSON(json: any): SwimlaneControllerDeleteSwimlaneResponse {
    return SwimlaneControllerDeleteSwimlaneResponseFromJSONTyped(json, false);
}

export function SwimlaneControllerDeleteSwimlaneResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwimlaneControllerDeleteSwimlaneResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'swimlane': json['swimlane'] == null ? undefined : ModelsSwimlaneFromJSON(json['swimlane']),
    };
}

export function SwimlaneControllerDeleteSwimlaneResponseToJSON(json: any): SwimlaneControllerDeleteSwimlaneResponse {
    return SwimlaneControllerDeleteSwimlaneResponseToJSONTyped(json, false);
}

export function SwimlaneControllerDeleteSwimlaneResponseToJSONTyped(value?: SwimlaneControllerDeleteSwimlaneResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'swimlane': ModelsSwimlaneToJSON(value['swimlane']),
    };
}

