/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SwimlaneControllerCreateSwimlaneRequest
 */
export interface SwimlaneControllerCreateSwimlaneRequest {
    /**
     * 
     * @type {number}
     * @memberof SwimlaneControllerCreateSwimlaneRequest
     */
    boardId?: number;
    /**
     * 
     * @type {string}
     * @memberof SwimlaneControllerCreateSwimlaneRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the SwimlaneControllerCreateSwimlaneRequest interface.
 */
export function instanceOfSwimlaneControllerCreateSwimlaneRequest(value: object): value is SwimlaneControllerCreateSwimlaneRequest {
    return true;
}

export function SwimlaneControllerCreateSwimlaneRequestFromJSON(json: any): SwimlaneControllerCreateSwimlaneRequest {
    return SwimlaneControllerCreateSwimlaneRequestFromJSONTyped(json, false);
}

export function SwimlaneControllerCreateSwimlaneRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwimlaneControllerCreateSwimlaneRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'boardId': json['board_id'] == null ? undefined : json['board_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function SwimlaneControllerCreateSwimlaneRequestToJSON(json: any): SwimlaneControllerCreateSwimlaneRequest {
    return SwimlaneControllerCreateSwimlaneRequestToJSONTyped(json, false);
}

export function SwimlaneControllerCreateSwimlaneRequestToJSONTyped(value?: SwimlaneControllerCreateSwimlaneRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'board_id': value['boardId'],
        'name': value['name'],
    };
}

