/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SwimlaneControllerDeleteSwimlaneRequest
 */
export interface SwimlaneControllerDeleteSwimlaneRequest {
    /**
     * 
     * @type {number}
     * @memberof SwimlaneControllerDeleteSwimlaneRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the SwimlaneControllerDeleteSwimlaneRequest interface.
 */
export function instanceOfSwimlaneControllerDeleteSwimlaneRequest(value: object): value is SwimlaneControllerDeleteSwimlaneRequest {
    return true;
}

export function SwimlaneControllerDeleteSwimlaneRequestFromJSON(json: any): SwimlaneControllerDeleteSwimlaneRequest {
    return SwimlaneControllerDeleteSwimlaneRequestFromJSONTyped(json, false);
}

export function SwimlaneControllerDeleteSwimlaneRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwimlaneControllerDeleteSwimlaneRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function SwimlaneControllerDeleteSwimlaneRequestToJSON(json: any): SwimlaneControllerDeleteSwimlaneRequest {
    return SwimlaneControllerDeleteSwimlaneRequestToJSONTyped(json, false);
}

export function SwimlaneControllerDeleteSwimlaneRequestToJSONTyped(value?: SwimlaneControllerDeleteSwimlaneRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

