/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsSwimlane } from './ModelsSwimlane';
import {
    ModelsSwimlaneFromJSON,
    ModelsSwimlaneFromJSONTyped,
    ModelsSwimlaneToJSON,
    ModelsSwimlaneToJSONTyped,
} from './ModelsSwimlane';

/**
 * 
 * @export
 * @interface SwimlaneControllerMoveSwimlaneResponse
 */
export interface SwimlaneControllerMoveSwimlaneResponse {
    /**
     * 
     * @type {ModelsSwimlane}
     * @memberof SwimlaneControllerMoveSwimlaneResponse
     */
    swimlane?: ModelsSwimlane;
}

/**
 * Check if a given object implements the SwimlaneControllerMoveSwimlaneResponse interface.
 */
export function instanceOfSwimlaneControllerMoveSwimlaneResponse(value: object): value is SwimlaneControllerMoveSwimlaneResponse {
    return true;
}

export function SwimlaneControllerMoveSwimlaneResponseFromJSON(json: any): SwimlaneControllerMoveSwimlaneResponse {
    return SwimlaneControllerMoveSwimlaneResponseFromJSONTyped(json, false);
}

export function SwimlaneControllerMoveSwimlaneResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwimlaneControllerMoveSwimlaneResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'swimlane': json['swimlane'] == null ? undefined : ModelsSwimlaneFromJSON(json['swimlane']),
    };
}

export function SwimlaneControllerMoveSwimlaneResponseToJSON(json: any): SwimlaneControllerMoveSwimlaneResponse {
    return SwimlaneControllerMoveSwimlaneResponseToJSONTyped(json, false);
}

export function SwimlaneControllerMoveSwimlaneResponseToJSONTyped(value?: SwimlaneControllerMoveSwimlaneResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'swimlane': ModelsSwimlaneToJSON(value['swimlane']),
    };
}

