/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsSwimlane } from './ModelsSwimlane';
import {
    ModelsSwimlaneFromJSON,
    ModelsSwimlaneFromJSONTyped,
    ModelsSwimlaneToJSON,
    ModelsSwimlaneToJSONTyped,
} from './ModelsSwimlane';

/**
 * 
 * @export
 * @interface SwimlaneControllerEditSwimlaneResponse
 */
export interface SwimlaneControllerEditSwimlaneResponse {
    /**
     * 
     * @type {ModelsSwimlane}
     * @memberof SwimlaneControllerEditSwimlaneResponse
     */
    swimlane?: ModelsSwimlane;
}

/**
 * Check if a given object implements the SwimlaneControllerEditSwimlaneResponse interface.
 */
export function instanceOfSwimlaneControllerEditSwimlaneResponse(value: object): value is SwimlaneControllerEditSwimlaneResponse {
    return true;
}

export function SwimlaneControllerEditSwimlaneResponseFromJSON(json: any): SwimlaneControllerEditSwimlaneResponse {
    return SwimlaneControllerEditSwimlaneResponseFromJSONTyped(json, false);
}

export function SwimlaneControllerEditSwimlaneResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwimlaneControllerEditSwimlaneResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'swimlane': json['swimlane'] == null ? undefined : ModelsSwimlaneFromJSON(json['swimlane']),
    };
}

export function SwimlaneControllerEditSwimlaneResponseToJSON(json: any): SwimlaneControllerEditSwimlaneResponse {
    return SwimlaneControllerEditSwimlaneResponseToJSONTyped(json, false);
}

export function SwimlaneControllerEditSwimlaneResponseToJSONTyped(value?: SwimlaneControllerEditSwimlaneResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'swimlane': ModelsSwimlaneToJSON(value['swimlane']),
    };
}

