/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SwimlaneControllerMoveSwimlaneRequest
 */
export interface SwimlaneControllerMoveSwimlaneRequest {
    /**
     * 
     * @type {string}
     * @memberof SwimlaneControllerMoveSwimlaneRequest
     */
    direction: SwimlaneControllerMoveSwimlaneRequestDirectionEnum;
    /**
     * 
     * @type {number}
     * @memberof SwimlaneControllerMoveSwimlaneRequest
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof SwimlaneControllerMoveSwimlaneRequest
     */
    relativeId: number;
}


/**
 * @export
 */
export const SwimlaneControllerMoveSwimlaneRequestDirectionEnum = {
    Before: 'before',
    After: 'after'
} as const;
export type SwimlaneControllerMoveSwimlaneRequestDirectionEnum = typeof SwimlaneControllerMoveSwimlaneRequestDirectionEnum[keyof typeof SwimlaneControllerMoveSwimlaneRequestDirectionEnum];


/**
 * Check if a given object implements the SwimlaneControllerMoveSwimlaneRequest interface.
 */
export function instanceOfSwimlaneControllerMoveSwimlaneRequest(value: object): value is SwimlaneControllerMoveSwimlaneRequest {
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('relativeId' in value) || value['relativeId'] === undefined) return false;
    return true;
}

export function SwimlaneControllerMoveSwimlaneRequestFromJSON(json: any): SwimlaneControllerMoveSwimlaneRequest {
    return SwimlaneControllerMoveSwimlaneRequestFromJSONTyped(json, false);
}

export function SwimlaneControllerMoveSwimlaneRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwimlaneControllerMoveSwimlaneRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'direction': json['direction'],
        'id': json['id'],
        'relativeId': json['relative_id'],
    };
}

export function SwimlaneControllerMoveSwimlaneRequestToJSON(json: any): SwimlaneControllerMoveSwimlaneRequest {
    return SwimlaneControllerMoveSwimlaneRequestToJSONTyped(json, false);
}

export function SwimlaneControllerMoveSwimlaneRequestToJSONTyped(value?: SwimlaneControllerMoveSwimlaneRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'direction': value['direction'],
        'id': value['id'],
        'relative_id': value['relativeId'],
    };
}

