/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsSwimlane } from './ModelsSwimlane';
import {
    ModelsSwimlaneFromJSON,
    ModelsSwimlaneFromJSONTyped,
    ModelsSwimlaneToJSON,
    ModelsSwimlaneToJSONTyped,
} from './ModelsSwimlane';

/**
 * 
 * @export
 * @interface SwimlaneControllerCreateSwimlaneResponse
 */
export interface SwimlaneControllerCreateSwimlaneResponse {
    /**
     * 
     * @type {ModelsSwimlane}
     * @memberof SwimlaneControllerCreateSwimlaneResponse
     */
    swimlane?: ModelsSwimlane;
}

/**
 * Check if a given object implements the SwimlaneControllerCreateSwimlaneResponse interface.
 */
export function instanceOfSwimlaneControllerCreateSwimlaneResponse(value: object): value is SwimlaneControllerCreateSwimlaneResponse {
    return true;
}

export function SwimlaneControllerCreateSwimlaneResponseFromJSON(json: any): SwimlaneControllerCreateSwimlaneResponse {
    return SwimlaneControllerCreateSwimlaneResponseFromJSONTyped(json, false);
}

export function SwimlaneControllerCreateSwimlaneResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwimlaneControllerCreateSwimlaneResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'swimlane': json['swimlane'] == null ? undefined : ModelsSwimlaneFromJSON(json['swimlane']),
    };
}

export function SwimlaneControllerCreateSwimlaneResponseToJSON(json: any): SwimlaneControllerCreateSwimlaneResponse {
    return SwimlaneControllerCreateSwimlaneResponseToJSONTyped(json, false);
}

export function SwimlaneControllerCreateSwimlaneResponseToJSONTyped(value?: SwimlaneControllerCreateSwimlaneResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'swimlane': ModelsSwimlaneToJSON(value['swimlane']),
    };
}

