/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsTask } from './ModelsTask';
import {
    ModelsTaskFromJSON,
    ModelsTaskFromJSONTyped,
    ModelsTaskToJSON,
    ModelsTaskToJSONTyped,
} from './ModelsTask';

/**
 * 
 * @export
 * @interface TaskControllerGetTaskResponse
 */
export interface TaskControllerGetTaskResponse {
    /**
     * 
     * @type {ModelsTask}
     * @memberof TaskControllerGetTaskResponse
     */
    task?: ModelsTask;
}

/**
 * Check if a given object implements the TaskControllerGetTaskResponse interface.
 */
export function instanceOfTaskControllerGetTaskResponse(value: object): value is TaskControllerGetTaskResponse {
    return true;
}

export function TaskControllerGetTaskResponseFromJSON(json: any): TaskControllerGetTaskResponse {
    return TaskControllerGetTaskResponseFromJSONTyped(json, false);
}

export function TaskControllerGetTaskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskControllerGetTaskResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'task': json['task'] == null ? undefined : ModelsTaskFromJSON(json['task']),
    };
}

export function TaskControllerGetTaskResponseToJSON(json: any): TaskControllerGetTaskResponse {
    return TaskControllerGetTaskResponseToJSONTyped(json, false);
}

export function TaskControllerGetTaskResponseToJSONTyped(value?: TaskControllerGetTaskResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task': ModelsTaskToJSON(value['task']),
    };
}

