/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskControllerDeleteTaskRequest
 */
export interface TaskControllerDeleteTaskRequest {
    /**
     * 
     * @type {number}
     * @memberof TaskControllerDeleteTaskRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the TaskControllerDeleteTaskRequest interface.
 */
export function instanceOfTaskControllerDeleteTaskRequest(value: object): value is TaskControllerDeleteTaskRequest {
    return true;
}

export function TaskControllerDeleteTaskRequestFromJSON(json: any): TaskControllerDeleteTaskRequest {
    return TaskControllerDeleteTaskRequestFromJSONTyped(json, false);
}

export function TaskControllerDeleteTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskControllerDeleteTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function TaskControllerDeleteTaskRequestToJSON(json: any): TaskControllerDeleteTaskRequest {
    return TaskControllerDeleteTaskRequestToJSONTyped(json, false);
}

export function TaskControllerDeleteTaskRequestToJSONTyped(value?: TaskControllerDeleteTaskRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

