/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsTask } from './ModelsTask';
import {
    ModelsTaskFromJSON,
    ModelsTaskFromJSONTyped,
    ModelsTaskToJSON,
    ModelsTaskToJSONTyped,
} from './ModelsTask';

/**
 * 
 * @export
 * @interface TaskControllerEditTaskResponse
 */
export interface TaskControllerEditTaskResponse {
    /**
     * 
     * @type {ModelsTask}
     * @memberof TaskControllerEditTaskResponse
     */
    task?: ModelsTask;
}

/**
 * Check if a given object implements the TaskControllerEditTaskResponse interface.
 */
export function instanceOfTaskControllerEditTaskResponse(value: object): value is TaskControllerEditTaskResponse {
    return true;
}

export function TaskControllerEditTaskResponseFromJSON(json: any): TaskControllerEditTaskResponse {
    return TaskControllerEditTaskResponseFromJSONTyped(json, false);
}

export function TaskControllerEditTaskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskControllerEditTaskResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'task': json['task'] == null ? undefined : ModelsTaskFromJSON(json['task']),
    };
}

export function TaskControllerEditTaskResponseToJSON(json: any): TaskControllerEditTaskResponse {
    return TaskControllerEditTaskResponseToJSONTyped(json, false);
}

export function TaskControllerEditTaskResponseToJSONTyped(value?: TaskControllerEditTaskResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task': ModelsTaskToJSON(value['task']),
    };
}

