/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskControllerGetTaskRequest
 */
export interface TaskControllerGetTaskRequest {
    /**
     * 
     * @type {number}
     * @memberof TaskControllerGetTaskRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the TaskControllerGetTaskRequest interface.
 */
export function instanceOfTaskControllerGetTaskRequest(value: object): value is TaskControllerGetTaskRequest {
    return true;
}

export function TaskControllerGetTaskRequestFromJSON(json: any): TaskControllerGetTaskRequest {
    return TaskControllerGetTaskRequestFromJSONTyped(json, false);
}

export function TaskControllerGetTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskControllerGetTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function TaskControllerGetTaskRequestToJSON(json: any): TaskControllerGetTaskRequest {
    return TaskControllerGetTaskRequestToJSONTyped(json, false);
}

export function TaskControllerGetTaskRequestToJSONTyped(value?: TaskControllerGetTaskRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

