/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsTask } from './ModelsTask';
import {
    ModelsTaskFromJSON,
    ModelsTaskFromJSONTyped,
    ModelsTaskToJSON,
    ModelsTaskToJSONTyped,
} from './ModelsTask';

/**
 * 
 * @export
 * @interface TaskControllerChangeAssigneeResponse
 */
export interface TaskControllerChangeAssigneeResponse {
    /**
     * 
     * @type {ModelsTask}
     * @memberof TaskControllerChangeAssigneeResponse
     */
    task?: ModelsTask;
}

/**
 * Check if a given object implements the TaskControllerChangeAssigneeResponse interface.
 */
export function instanceOfTaskControllerChangeAssigneeResponse(value: object): value is TaskControllerChangeAssigneeResponse {
    return true;
}

export function TaskControllerChangeAssigneeResponseFromJSON(json: any): TaskControllerChangeAssigneeResponse {
    return TaskControllerChangeAssigneeResponseFromJSONTyped(json, false);
}

export function TaskControllerChangeAssigneeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskControllerChangeAssigneeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'task': json['task'] == null ? undefined : ModelsTaskFromJSON(json['task']),
    };
}

export function TaskControllerChangeAssigneeResponseToJSON(json: any): TaskControllerChangeAssigneeResponse {
    return TaskControllerChangeAssigneeResponseToJSONTyped(json, false);
}

export function TaskControllerChangeAssigneeResponseToJSONTyped(value?: TaskControllerChangeAssigneeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task': ModelsTaskToJSON(value['task']),
    };
}

