/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsTask } from './ModelsTask';
import {
    ModelsTaskFromJSON,
    ModelsTaskFromJSONTyped,
    ModelsTaskToJSON,
    ModelsTaskToJSONTyped,
} from './ModelsTask';

/**
 * 
 * @export
 * @interface TaskControllerMoveTaskResponse
 */
export interface TaskControllerMoveTaskResponse {
    /**
     * 
     * @type {ModelsTask}
     * @memberof TaskControllerMoveTaskResponse
     */
    task?: ModelsTask;
}

/**
 * Check if a given object implements the TaskControllerMoveTaskResponse interface.
 */
export function instanceOfTaskControllerMoveTaskResponse(value: object): value is TaskControllerMoveTaskResponse {
    return true;
}

export function TaskControllerMoveTaskResponseFromJSON(json: any): TaskControllerMoveTaskResponse {
    return TaskControllerMoveTaskResponseFromJSONTyped(json, false);
}

export function TaskControllerMoveTaskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskControllerMoveTaskResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'task': json['task'] == null ? undefined : ModelsTaskFromJSON(json['task']),
    };
}

export function TaskControllerMoveTaskResponseToJSON(json: any): TaskControllerMoveTaskResponse {
    return TaskControllerMoveTaskResponseToJSONTyped(json, false);
}

export function TaskControllerMoveTaskResponseToJSONTyped(value?: TaskControllerMoveTaskResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task': ModelsTaskToJSON(value['task']),
    };
}

