/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskControllerChangeAssigneeRequest
 */
export interface TaskControllerChangeAssigneeRequest {
    /**
     * 
     * @type {number}
     * @memberof TaskControllerChangeAssigneeRequest
     */
    assigneeId?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskControllerChangeAssigneeRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the TaskControllerChangeAssigneeRequest interface.
 */
export function instanceOfTaskControllerChangeAssigneeRequest(value: object): value is TaskControllerChangeAssigneeRequest {
    return true;
}

export function TaskControllerChangeAssigneeRequestFromJSON(json: any): TaskControllerChangeAssigneeRequest {
    return TaskControllerChangeAssigneeRequestFromJSONTyped(json, false);
}

export function TaskControllerChangeAssigneeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskControllerChangeAssigneeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'assigneeId': json['assignee_id'] == null ? undefined : json['assignee_id'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function TaskControllerChangeAssigneeRequestToJSON(json: any): TaskControllerChangeAssigneeRequest {
    return TaskControllerChangeAssigneeRequestToJSONTyped(json, false);
}

export function TaskControllerChangeAssigneeRequestToJSONTyped(value?: TaskControllerChangeAssigneeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assignee_id': value['assigneeId'],
        'id': value['id'],
    };
}

