/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsTask } from './ModelsTask';
import {
    ModelsTaskFromJSON,
    ModelsTaskFromJSONTyped,
    ModelsTaskToJSON,
    ModelsTaskToJSONTyped,
} from './ModelsTask';

/**
 * 
 * @export
 * @interface TaskControllerGetTaskQueryResponse
 */
export interface TaskControllerGetTaskQueryResponse {
    /**
     * 
     * @type {Array<ModelsTask>}
     * @memberof TaskControllerGetTaskQueryResponse
     */
    tasks?: Array<ModelsTask>;
}

/**
 * Check if a given object implements the TaskControllerGetTaskQueryResponse interface.
 */
export function instanceOfTaskControllerGetTaskQueryResponse(value: object): value is TaskControllerGetTaskQueryResponse {
    return true;
}

export function TaskControllerGetTaskQueryResponseFromJSON(json: any): TaskControllerGetTaskQueryResponse {
    return TaskControllerGetTaskQueryResponseFromJSONTyped(json, false);
}

export function TaskControllerGetTaskQueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskControllerGetTaskQueryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tasks': json['tasks'] == null ? undefined : ((json['tasks'] as Array<any>).map(ModelsTaskFromJSON)),
    };
}

export function TaskControllerGetTaskQueryResponseToJSON(json: any): TaskControllerGetTaskQueryResponse {
    return TaskControllerGetTaskQueryResponseToJSONTyped(json, false);
}

export function TaskControllerGetTaskQueryResponseToJSONTyped(value?: TaskControllerGetTaskQueryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tasks': value['tasks'] == null ? undefined : ((value['tasks'] as Array<any>).map(ModelsTaskToJSON)),
    };
}

