/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskControllerEditTaskRequest
 */
export interface TaskControllerEditTaskRequest {
    /**
     * 
     * @type {number}
     * @memberof TaskControllerEditTaskRequest
     */
    columnId?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskControllerEditTaskRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof TaskControllerEditTaskRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskControllerEditTaskRequest
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof TaskControllerEditTaskRequest
     */
    swimlaneId?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskControllerEditTaskRequest
     */
    title?: string;
}

/**
 * Check if a given object implements the TaskControllerEditTaskRequest interface.
 */
export function instanceOfTaskControllerEditTaskRequest(value: object): value is TaskControllerEditTaskRequest {
    return true;
}

export function TaskControllerEditTaskRequestFromJSON(json: any): TaskControllerEditTaskRequest {
    return TaskControllerEditTaskRequestFromJSONTyped(json, false);
}

export function TaskControllerEditTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskControllerEditTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'columnId': json['column_id'] == null ? undefined : json['column_id'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : json['status'],
        'swimlaneId': json['swimlane_id'] == null ? undefined : json['swimlane_id'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function TaskControllerEditTaskRequestToJSON(json: any): TaskControllerEditTaskRequest {
    return TaskControllerEditTaskRequestToJSONTyped(json, false);
}

export function TaskControllerEditTaskRequestToJSONTyped(value?: TaskControllerEditTaskRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'column_id': value['columnId'],
        'description': value['description'],
        'id': value['id'],
        'status': value['status'],
        'swimlane_id': value['swimlaneId'],
        'title': value['title'],
    };
}

