/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsTask } from './ModelsTask';
import {
    ModelsTaskFromJSON,
    ModelsTaskFromJSONTyped,
    ModelsTaskToJSON,
    ModelsTaskToJSONTyped,
} from './ModelsTask';

/**
 * 
 * @export
 * @interface TaskControllerDeleteTaskResponse
 */
export interface TaskControllerDeleteTaskResponse {
    /**
     * 
     * @type {ModelsTask}
     * @memberof TaskControllerDeleteTaskResponse
     */
    task?: ModelsTask;
}

/**
 * Check if a given object implements the TaskControllerDeleteTaskResponse interface.
 */
export function instanceOfTaskControllerDeleteTaskResponse(value: object): value is TaskControllerDeleteTaskResponse {
    return true;
}

export function TaskControllerDeleteTaskResponseFromJSON(json: any): TaskControllerDeleteTaskResponse {
    return TaskControllerDeleteTaskResponseFromJSONTyped(json, false);
}

export function TaskControllerDeleteTaskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskControllerDeleteTaskResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'task': json['task'] == null ? undefined : ModelsTaskFromJSON(json['task']),
    };
}

export function TaskControllerDeleteTaskResponseToJSON(json: any): TaskControllerDeleteTaskResponse {
    return TaskControllerDeleteTaskResponseToJSONTyped(json, false);
}

export function TaskControllerDeleteTaskResponseToJSONTyped(value?: TaskControllerDeleteTaskResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task': ModelsTaskToJSON(value['task']),
    };
}

