/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskControllerCreateTaskRequest
 */
export interface TaskControllerCreateTaskRequest {
    /**
     * 
     * @type {number}
     * @memberof TaskControllerCreateTaskRequest
     */
    boardId?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskControllerCreateTaskRequest
     */
    columnId?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskControllerCreateTaskRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskControllerCreateTaskRequest
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof TaskControllerCreateTaskRequest
     */
    swimlaneId?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskControllerCreateTaskRequest
     */
    title?: string;
}

/**
 * Check if a given object implements the TaskControllerCreateTaskRequest interface.
 */
export function instanceOfTaskControllerCreateTaskRequest(value: object): value is TaskControllerCreateTaskRequest {
    return true;
}

export function TaskControllerCreateTaskRequestFromJSON(json: any): TaskControllerCreateTaskRequest {
    return TaskControllerCreateTaskRequestFromJSONTyped(json, false);
}

export function TaskControllerCreateTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskControllerCreateTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'boardId': json['board_id'] == null ? undefined : json['board_id'],
        'columnId': json['column_id'] == null ? undefined : json['column_id'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : json['status'],
        'swimlaneId': json['swimlane_id'] == null ? undefined : json['swimlane_id'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function TaskControllerCreateTaskRequestToJSON(json: any): TaskControllerCreateTaskRequest {
    return TaskControllerCreateTaskRequestToJSONTyped(json, false);
}

export function TaskControllerCreateTaskRequestToJSONTyped(value?: TaskControllerCreateTaskRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'board_id': value['boardId'],
        'column_id': value['columnId'],
        'description': value['description'],
        'status': value['status'],
        'swimlane_id': value['swimlaneId'],
        'title': value['title'],
    };
}

