/* tslint:disable */
/* eslint-disable */
/**
 * Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskControllerGetTaskQueryRequest
 */
export interface TaskControllerGetTaskQueryRequest {
    /**
     * 
     * @type {string}
     * @memberof TaskControllerGetTaskQueryRequest
     */
    query?: string;
}

/**
 * Check if a given object implements the TaskControllerGetTaskQueryRequest interface.
 */
export function instanceOfTaskControllerGetTaskQueryRequest(value: object): value is TaskControllerGetTaskQueryRequest {
    return true;
}

export function TaskControllerGetTaskQueryRequestFromJSON(json: any): TaskControllerGetTaskQueryRequest {
    return TaskControllerGetTaskQueryRequestFromJSONTyped(json, false);
}

export function TaskControllerGetTaskQueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskControllerGetTaskQueryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'] == null ? undefined : json['query'],
    };
}

export function TaskControllerGetTaskQueryRequestToJSON(json: any): TaskControllerGetTaskQueryRequest {
    return TaskControllerGetTaskQueryRequestToJSONTyped(json, false);
}

export function TaskControllerGetTaskQueryRequestToJSONTyped(value?: TaskControllerGetTaskQueryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
    };
}

