# this is a docker compose file used for local development

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8090:8090"
    volumes:
      - ./server:/go/src/app
      - ./data:/data
    environment:
      - SQLITE_FILE_PATH=/data/sqlite.db
      - DATA_DIR=/data/data
      - SMTP_PORT=1025
      - SMTP_NO_TLS=true
      - SMTP_HOST=mailpit

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./client:/usr/src/app

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailpit-data:/data

volumes:
  mailpit-data:
