name: "Common Steps"
description: "Reusable steps for lint and test jobs."
inputs:
  working-directory:
    description: "Subdirectory in which to run the commands"
    required: false
    default: "server"
runs:
  using: "composite"
  steps:
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ${{ inputs.working-directory }}/pkg/mod
          ${{ inputs.working-directory }}/go.sum
        key: ${{ runner.os }}-go-${{ hashFiles(format('{0}/go.sum', inputs.working-directory)) }}

    - name: Download Dependencies
      run: cd ${{ inputs.working-directory }} && go mod download
      shell: bash

    - name: Install swag CLI
      run: cd ${{ inputs.working-directory }} && go install github.com/swaggo/swag/cmd/swag@latest
      shell: bash

    - name: Generate Swagger docs
      run: cd ${{ inputs.working-directory }} && swag init --pd --parseInternal -g cmd/main.go
      shell: bash
      continue-on-error: true
