export const friendlyEventNames: Record<string, string> = {
  "task.created": "Task created",
  "task.updated.title": "Task title updated",
  "task.updated.description": "Task description updated",
  "task.updated.status": "Task status updated",
  "task.updated.assignee": "Task assignee updated",
  "task.updated.due-date": "Task due date updated",
  "task.deleted": "Task deleted",
  "task.moved": "Task moved",
  "comment.created": "Comment created",
  "comment.updated": "Comment updated",
  "comment.deleted": "Comment deleted",
  "file.created": "File created",
  "file.updated": "File updated",
  "file.deleted": "File deleted",
  "link.created": "Link created",
  "link.deleted": "Link deleted",
  "externallink.created": "External link created",
  "externallink.updated": "External link updated",
  "externallink.deleted": "External link deleted",
  "reaction.created": "Comment reaction created",
  "reaction.deleted": "Comment reaction deleted",
};
