name: "Common Steps"
description: "Reusable steps for lint and test jobs."
inputs: {}
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          server/pkg/mod
          server/go.sum
        key: ${{ runner.os }}-go-${{ hashFiles('server/go.sum') }}

    - name: Download Dependencies
      run: go mod download

    - name: Install swag CLI
      run: go install github.com/swaggo/swag/cmd/swag@latest

    - name: Generate Swagger docs
      run: swag init --pd --parseInternal -g cmd/main.go
      continue-on-error: true
