name: Docker Image Build and Push CI

on:
  push:
    tags:
      - "*"

jobs:
  build_and_push:
    name: Build and push Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install aarch64-linux-gnu-gcc
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Download Dependencies
        run: go mod download
        working-directory: server

      - name: Install swag CLI
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger docs (server)
        run: swag init --pd --parseInternal -g cmd/main.go
        working-directory: server
        continue-on-error: true

      - name: Generate API client (client)
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-fetch
          openapi-file: server/docs/swagger.yaml
          command-args: -o client/src/typescript-fetch-client

      - name: Cross-compile server binaries
        run: |
          mkdir -p ../bin
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o ../bin/server-amd64 cmd/main.go
          CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc go build -o ../bin/server-arm64 cmd/main.go
        working-directory: server

      - name: Install and build client
        run: |
          npm ci
          npm run build
        working-directory: client

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Server - Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/kanban-server:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/kanban-server:latest

      - name: Client - Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: client/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/kanban-client:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/kanban-client:latest
