name: Lint and test server

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

steps-common: &common-steps
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Set up Go
    uses: actions/setup-go@v4
    with:
      go-version: 1.23

  - name: Cache Go modules
    uses: actions/cache@v3
    with:
      path: |
        server/pkg/mod
        server/go.sum
      key: ${{ runner.os }}-go-${{ hashFiles('server/go.sum') }}

  - name: Download Dependencies
    run: go mod download

  - name: Install swag CLI
    run: go install github.com/swaggo/swag/cmd/swag@latest

  - name: Generate Swagger docs
    run: swag init --pd --parseInternal -g cmd/main.go
    continue-on-error: true

jobs:
  lint:
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest
    steps:
      <<: *common-steps
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m

  test:
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest
    steps:
      <<: *common-steps
      - name: Run Go tests
        run: go test -v ./...
