name: Lint and test server

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run common steps
        uses: ./.github/actions/common-steps
      - name: Uninstall Go
        run: |
          echo "Uninstalling Go..."
          sudo rm -rf "$(go env GOROOT)"
          echo "Go uninstalled"
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m

  test:
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run common steps
        uses: ./.github/actions/common-steps
      - name: Run Go tests
        run: go test -v ./...
