name: Lint and test server

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  prepare:
    name: Prepare Generated Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
      - name: Run common steps
        uses: ./.github/actions/common-steps
        with:
          working-directory: server
      - name: Upload generated files
        uses: actions/upload-artifact@v4
        with:
          name: generated-files
          path: server

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download generated files
        uses: actions/download-artifact@v4
        with:
          name: generated-files
          path: server
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: prepare
    defaults:
      run:
        working-directory: server
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download generated files
        uses: actions/download-artifact@v4
        with:
          name: generated-files
          path: server
      - name: Run Go tests
        run: go test -v ./...
